############################################################
# packages
############################################################

############################################################
#
# Chicken Coop Automation and Sensors
#
############################################################

# binary_sensor threshold does not support states for limits and we are forced to use a hardcoded values!
# https://community.home-assistant.io/t/use-template-for-binary-sensor-threshold/66577

# https://www.home-assistant.io/integrations/threshold/
binary_sensor:
  - platform: threshold
    name: Chicken Low Food Sensor
    entity_id: sensor.chicken_house_food_level #From EspHome Sensor
    lower: 0.6
    device_class: problem
    hysteresis: 0.1

  - platform: threshold
    name: Chicken Low Water Sensor
    entity_id: sensor.chicken_house_water_level #From EspHome Sensor
    lower: 0.6
    device_class: problem
    hysteresis: 0.1

# Not used, as the moment as threshold does not support it.
# https://www.home-assistant.io/integrations/input_number/
input_number:
  chicken_food_low_level_input:
    name: Chicken Food Low Level Setpoint
    initial: 0.5
    min: 0.01
    max: 3
    step: 0.01
    unit_of_measurement: kg
  chicken_water_low_level_input:
    name: Chicken Water Low Level Setpoint
    initial: 0.5
    min: 0.01
    max: 3
    step: 0.01
    unit_of_measurement: kg

# https://www.home-assistant.io/integrations/alert/
alert:
  chicken_food_low_alert:
    name: Chicken food low warning alert
    done_message: Chickens Food Refilled
    message: "Chicken Food Low Warning! {{ states('sensor.chicken_house_food_level') }}kg"
    entity_id: binary_sensor.chicken_low_food_sensor
    state: "on"
    repeat:
      - 240
      - 120
      - 60
    can_acknowledge: true
    skip_first: false
    data:
      channel: Chickens2
      color: brown
      importance: default
      visibility: public
      notification_icon: mdi:egg
    notifiers:
      - mobile_app_rich_mob_app
      - mobile_app_lucy_mob_app

  chicken_water_low_alert:
    name: Chicken water low warning alert
    done_message: Chickens Water Refilled
    message: "Chicken Water Low Warning! {{ states('sensor.chicken_house_water_level') }}kg"
    entity_id: binary_sensor.chicken_low_water_sensor
    state: "on"
    repeat:
      - 240
      - 120
      - 60
    can_acknowledge: true
    skip_first: false
    data:
      channel: Chickens2
      color: brown
      importance: default
      visibility: public
      notification_icon: mdi:egg
    notifiers:
      - mobile_app_rich_mob_app
      - mobile_app_lucy_mob_app
