############################################################
#
# Chicken Coop Door Status
#
############################################################

# Icon set in homeassistant:customize
- platform: mqtt
  state_topic: "HUISHS/Chickens/Door/State"
  name: "Chicken Door Status"
  payload_on: "OPENED"
  payload_off: "CLOSED"
  device_class: door #Classes https://home-assistant.io/components/binary_sensor/
  availability_topic: "HUISHS/Chickens/Door/Status"
  payload_available: "online"
  payload_not_available: "offline"
