############################################################
#
# Home Assistant Binary Sensors
#
############################################################

############################################################
#
# Lighting Gateway Status
#
############################################################

# 2017 disabled
# Ref: https://github.com/home-assistant/home-assistant/issues/6876
# - platform: mqtt
#   state_topic: "HUISHS/LightingGateway/Status"
#   name: "RF Gateway Status"
#   qos: 0
#   payload_on: "online"
#   payload_off: "offline"
#   device_class: connectivity


############################################################
#
# Bunny Shed Heating Controller Status
#
############################################################

- platform: mqtt
  state_topic: "HUISHS/BunnyShed/status"
  name: "Bunny Shed Controller Status"
  qos: 0
  payload_on: "online"
  payload_off: "offline"
  device_class: connectivity


############################################################
#
# Doorbell Controller Status
#
############################################################

- platform: mqtt
  state_topic: "HUISHS/Doorbell/Status"
  name: "Doorbell Controller Status"
  qos: 0
  payload_on: "online"
  payload_off: "offline"
  device_class: connectivity

############################################################
#
# RFLink Gateway
#
############################################################

- platform: template
  sensors:
    rflink_status:
      friendly_name: 'RFLink Gateway Status'
      device_class: 'connectivity'
      value_template: "{% if is_state('rflink.connection_status', 'connected') %}true{% else %}false{% endif %}"


############################################################
#
# ESP-Link Gateway
#
############################################################

- platform: template
  sensors:
    esp_link_status:
      friendly_name: 'ESP-Link Gateway Status'
      device_class: 'connectivity'
      value_template: "{% if is_state('sensor.esplink_controller_signal_strength', 'unknown') %}false{% else %}true{% endif %}"
