############################################################
#
# Binary Irrigation Sensors
#
############################################################

# NO LONGER USED IN LUE OF TEMPLATE SENSORS
# # Pots Weather Interlock
# # Only water the lawn if its not too cold
#   - platform: template
#     sensors:
#       pots_irrigation_interlock:
#         friendly_name: "Weather Interlock"
#         device_class: problem
#         value_template: >
#          {% if
#          states('sensor.dark_sky_overnight_low_temperature_0d') | int > 5 %}
#          false
#          {% else %}
#          true
#          {% endif %}
#
# # Lawn Weather Interlock
# # Only water the lawn if its not going to rain, its not windy and its not too cold
# # sensor.dark_sky_precip_intensity_0d must be multipled by 24 to give a days worth of rain.
#   - platform: template
#     sensors:
#       lawn_irrigation_interlock:
#         friendly_name: "Weather Interlock"
#         device_class: problem
#         value_template: >
#          {% if
#          states('sensor.dark_sky_precip_intensity_0d') | multiply(24) | int > 5 %}
#          and
#          states('sensor.dark_sky_wind_speed') | int < 15
#          and
#          states('sensor.dark_sky_overnight_low_temperature_0d') | int > 5 %}
#          false
#          {% else %}
#          true
#          {% endif %}

- platform: template
  sensors:
      front_garden_pot_irrigation_valve_position:
          friendly_name: 'Valve Position'
          value_template: "{{ is_state('switch.front_garden_pot_irrigation_valve', 'on') }}"

- platform: template
  sensors:
      front_garden_lawn_irrigation_valve_position:
          friendly_name: 'Valve Position'
          value_template: "{{ is_state('switch.front_garden_lawn_irrigation_valve', 'on') }}"

- platform: template
  sensors:
      back_garden_irrigation_valve_position:
          friendly_name: 'Valve Position'
          value_template: "{{ is_state('switch.back_garden_irrigation_valve', 'on') }}"

- platform: template
  sensors:
      back_garden_lawn_1_irrigation_valve_position:
          friendly_name: 'Valve 1 Position'
          value_template: "{{ is_state('switch.back_garden_lawn_1_irrigation_valve', 'on') }}"

- platform: template
  sensors:
      back_garden_lawn_2_irrigation_valve_position:
          friendly_name: 'Valve 2 Position'
          value_template: "{{ is_state('switch.back_garden_lawn_2_irrigation_valve', 'on') }}"
