############################################################
#
# RFLink Binary Sensor
#
############################################################

# 433MHz automated add
- platform: rflink
  automatic_add: true
  device_defaults:
    fire_event: true
    signal_repetitions: 10
#
#
# - platform: rflink
#   devices:
#     ev1527_05d797_0e:
#       name: 'Front Door'
#       device_class: door
#       off_delay: 4
#       force_update: true

# # Repurposed door sensor for parcel box. No longer in use 2023
# - platform: rflink
#   devices:
#     eurodomest_2a2868_01:
#       name: "Parcel Box Sensor"
#       device_class: opening
#       off_delay: 4
#       force_update: true
#       # aliases:
#       #   - ev1527_01e9f5_07
#       #   - ev1527_05d797_0e

# # Has issues https://community.home-assistant.io/t/implement-rflink-ping/127033/3

# ############################################################
# #
# # RFLink TCP integration Binary Sensor Keep Connection alive
# # As fix is not working https://github.com/home-assistant/home-assistant.io/pull/16527
# #
# ############################################################

# - platform: tcp
#   name: RFLink Keep Alive TCP
#   host: !secret RF_Link_IP
#   port: !secret RF_Link_Port
#   payload: '10;PING'
#   value_on: 'pong'
#   value_template: "{{ value.split(';')[2] }}"

