############################################################
#
# RFLink Binary Sensor
#
############################################################

# - platform: rflink
#   devices:
#     ev1527_05d797_0e:
#       name: 'Front Door'
#       device_class: door
#       off_delay: 4
#       force_update: true

# Repurposed door sensor for parcel box
- platform: rflink
  devices:
    eurodomest_2a2868_01:
      name: "Parcel Box Sensor"
      device_class: opening
      off_delay: 4
      force_update: true
      # aliases:
      #   - ev1527_01e9f5_07
      #   - ev1527_05d797_0e

############################################################
#
# ESP-Link to RFLink Gateway
#
############################################################

- platform: template
  sensors:
    esp_link_status:
      friendly_name: "ESP-Link Gateway Status"
      device_class: "connectivity"
      value_template: "{% if is_state('sensor.esp_link_controller_signal_strength', 'unknown') %}false{% else %}true{% endif %}"
