- alias: "heat towel rail mqtt"
  trigger:
    - platform: mqtt
      topic: HUISHS/Button1/set
    # Optional
      payload: '1'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_heat_towel_rail

- alias: "dont heat towel rail mqtt"
  trigger:
    - platform: mqtt
      topic: HUISHS/Button1/set
    # Optional
      payload: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: script.turn_off_heat_towel_rail



# 
# - alias: "Dash Button Lights Off"
#   trigger:
#     - platform: mqtt
#       topic: HUISHS/dash
#     # Optional
#       payload: 'on'
#   action:
#     service: homeassistant.turn_off
#     entity_id: group.christmas_lights

#garage_door:
 # platform: mqtt
  #state_topic: "home-assistant/garage-door"
#  command_topic: "home-assistant/garage-door/set"
 # name: "MQTT Sensor"
  #optimistic: false
#  qos: 0
 # retain: true
  #state_open: "STATE_OPEN"
#  state_closed: "STATE_CLOSED"
 # service_open: "SERVICE_OPEN"
  #service_close: "SERVICE_CLOSE"
#  value_template: '{{ value.x }}'


#automation:
#  alias: "Heat Towel Rail For An Hour"
#  trigger:
#    - platform: state
#      entity_id: input_boolean.task_heat_towel_rail
#      to: 'on'
#  action:
#    service: homeassistant.turn_on
#    entity_id: script.timed_heat_towel_rail
