############################################################
#
# Amazon dash button automation
#
############################################################


- alias: "Dash Button Hall light on"
  trigger:
    platform: mqtt
    topic: HUISHS/dash1
    payload: 'on' # Payload is allways on, even when turing the lights off.
  condition:
    condition: state
    entity_id: light.lamp_4 #upstairs_hall_light
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: light.lamp_4 #upstairs_hall_light

- alias: "Dash Button Hall light off"
  trigger:
    platform: mqtt
    topic: HUISHS/dash1
    payload: 'on' # Payload is allways on, even when turing the lights off.
  condition:
    condition: state
    entity_id: light.lamp_4 #upstairs_hall_light
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: light.lamp_4 #upstairs_hall_light
