############################################################
#
#  Irrigation Schedule set time (Option 1)
# https://community.home-assistant.io/t/hass-sprinkler/1903/30?u=richard.huish
# Time trigger issues: https://community.home-assistant.io/t/hass-sprinkler/1903/62?u=richard.huish
#
############################################################


# - alias: Irrigation Schedule AM On
#   trigger:
#     platform: time
#     after: '07:00:00'
#   action:
#     service: homeassistant.turn_on
#     entity_id: script.irrigation_timer

############################################################
#
#  Irrigation Schedule auto time Lawn
#  Only runs when is not forecasted to rain, its not too windy
#  and the forecasted low is above 5 degrees centigrade.
#
############################################################
- alias: Irrigate Lawn at Sunrise
  trigger:
    platform: template
    # Trigger every day when time is right, but use conditions to only run on the scheduled days.
    value_template: '{{states.sensor.time.state == states.sensor.irrigation_starttime.state}}'
    # platform: sun
    # event: sunrise
    # offset: "+01:30:00" # Run 1.5 hours after dawn
  condition:
   condition: and
   conditions:
   - condition: template
     # Only run on scheduled days.
     value_template: "{{states.sensor.lawn_irrigation_next_run.state[5:15] == now().date().strftime('%d-%m-%Y')}}"

   # Issue with getting rainfall, have turned this off.
   # - condition: state
   #   entity_id: 'binary_sensor.lawn_irrigation_interlock'
   #   state: 'off'

  action:
    service: homeassistant.turn_on
    entity_id: script.lawn_irrigation_timer

###OLD method
# look into https://community.home-assistant.io/t/hass-sprinkler/1903/30?u=richard.huish

# - alias: Irrigate Lawn at Sunrise
#   trigger:
#     platform: sun
#     event: sunrise
#     offset: "+01:30:00" # Run 1.5 hours after dawn
#   condition:
#    condition: and
#    conditions:
#      # Don't water it is raining today (Forcasted using wunderground)
#    - condition: numeric_state
#      entity_id: sensor.pws_precip_today_metric
#      below: 5 # 5mm of rain.

#      # Don't water it is very windy right this moment.
#    - condition: numeric_state
#      entity_id: sensor.pws_wind_mph
#      below: 10

#      # Only water every few days
#    - condition: time
#      weekday:
#        - tue
#        - thu
#        - sat

#     # To protect the plants and pipes, don't run if the forecasted low is above 5 degrees centigrade
#     # (Should be off in winter anyways)
#    - condition: numeric_state
#      entity_id: sensor.pws_temp_low_1d_c
#      above: 5

#   action:
#     service: homeassistant.turn_on
#     entity_id: script.lawn_irrigation_timer




############################################################
#
#  Irrigation Schedule auto time pots
#
############################################################
- alias: Irrigate Pots at Sunrise
  trigger:
    platform: template
    # Trigger every day when time is right, but use conditions to only run on the scheduled days.
    value_template: '{{states.sensor.time.state == states.sensor.irrigation_starttime.state}}'
    # platform: sun
    # event: sunrise
    # offset: "+01:30:00" # Run 1.5 hours after dawn
  # condition:
  #  condition: and
  #  conditions:
  #  - condition: template
  #   # Only run on scheduled days.
  #    value_template: "{{states.sensor.pot_irrigation_next_run.state[5:15] == now().date().strftime('%d-%m-%Y')}}"

  # Issue with getting rainfall, have turned this off.
  #  - condition: state
  #    entity_id: 'binary_sensor.pots_irrigation_interlock'
  #    state: 'off'

  action:
    service: homeassistant.turn_on
    entity_id: script.pot_irrigation_timer

###OLD method
# - alias: Irrigate Pots at Sunrise
#   trigger:
#     platform: sun
#     event: sunrise
#   condition:
#     # Still run, even if its going to rain rain today.

#     # To protect the plants and pipes, don't run if the forecasted low is above 5 degrees centigrade
#     # (Should be off in winter anyways)
#    - condition: numeric_state
#      entity_id: sensor.pws_temp_low_1d_c
#      above: 5

#   action:
#     service: homeassistant.turn_on
#     entity_id: script.pot_irrigation_timer



#### OLDER method.
# - alias: Irrigation Schedule AM On
#   trigger:
#     platform: time
#     after: '07:00:00'
#   action:
#     service: switch.turn_on
#     entity_id: switch.irrigation_switch


# - alias: Irrigation Schedule AM Off
#   trigger:
#     platform: time
#     after: '07:15:00'
#   action:
#     service: switch.turn_off
#     entity_id: switch.irrigation_switch
