############################################################
#
#  Irrigation Schedule set time (Option 1)
#
############################################################


# - alias: Irrigation Schedule AM On
#   trigger:
#     platform: time
#     after: '07:00:00'
#   action:
#     service: homeassistant.turn_on
#     entity_id: script.irrigation_timer

############################################################
#
#  Irrigation Schedule auto time Lawn
#
############################################################
# look into https://community.home-assistant.io/t/hass-sprinkler/1903/30?u=richard.huish

- alias: Irrigate Lawn at Sunrise
  trigger:
    platform: sun
    event: sunrise
    offset: "+01:30:00"
  condition:
   condition: and
   conditions:
     # Don't water it is raining today
   - condition: numeric_state
     entity_id: sensor.precip_1d_metric
     below: 3
     # Only water every few days
   - condition: time
     weekday:
       - tue
       - thu
       - sat
  action:
    service: homeassistant.turn_on
    entity_id: script.lawn_irrigation_timer


############################################################
#
#  Irrigation Schedule auto time pots
#
############################################################

- alias: Irrigate Pots at Sunrise
  trigger:
    platform: sun
    event: sunrise
    # Time offset, to start action once Lawn irrigation duration has elapsed.
    # TODO: Offset NOT WORKING
    #offset: '00:{{states.input_slider.lawn_irrigation_duration.state|round(0)}}:00'
  condition:
    #To do its not raining today
  action:
    service: homeassistant.turn_on
    entity_id: script.pot_irrigation_timer


#### OLD method.
# - alias: Irrigation Schedule AM On
#   trigger:
#     platform: time
#     after: '07:00:00'
#   action:
#     service: switch.turn_on
#     entity_id: switch.irrigation_switch


# - alias: Irrigation Schedule AM Off
#   trigger:
#     platform: time
#     after: '07:15:00'
#   action:
#     service: switch.turn_off
#     entity_id: switch.irrigation_switch
