############################################################
#
#  Kitchen Extractor
#  If on button is pressed twise, enabble auto turn off
#
############################################################

- alias: Kitchen Extractor Enable Auto Off
  trigger:
    platform: state
    entity_id: switch.kitchen_extractor_fan
    from: 'off'
    to: 'on'
  action:
    service: script.turn_on
    data:
      entity_id: script.kitchen_extractor_timer

