############################################################
#
#  Automation Simulate Presence / Occupancy Simulation
#  Source: https://github.com/mertenats/Open-Home-Automation/blob/master/openhome/configuration/home_assistant/automation/automation_4a.yaml
#
############################################################

- alias: Simulate Presence
  trigger:
    - platform: state
      entity_id: group.all_devices
      from: 'home'
      to: 'not_home'
    - platform: sun
      event: sunset
      offset: "+00:30:00"
    - platform: event
      event_type: event_simulate_presence
  condition:  
    condition: and
    conditions:
      - condition: state
        entity_id: 'sun.sun'
        state: 'below_horizon'
      # Randomise when the lights all turn off
      - condition: time
        before: '23:01:00'
        #before: '23:{{ (range(01, 59) | random) }}:00'
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'
  action:
    - service: light.turn_on
    # Choose a lamp at random (between 1 and 4) and turn it on.
      data_template:
         entity_id: >
           light.lamp_{{ (range(1, 5) | random) }}
    # Keep lamp on for xx minutes)
    - delay: '00:{{ (range(10, 30) | random) }}:00'
    # turn off all lamps
    - service: light.turn_off
      entity_id:
        - light.lamp_1
        - light.lamp_2
        - light.lamp_3
        - light.lamp_4
    # wait a a few seconds before turning on another lamp
    - delay: '00:00:{{ (range(3, 10) | random) }}'  
    # generate an event to call again this automation rule
    - event: event_simulate_presence