- id: '1529279555355'
  alias: Reset Front Door Sensor
  trigger:
  - entity_id: switch.front_door_sensor
    from: 'off'
    platform: state
    to: 'on'
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: 00:00:05
  - data:
      entity_id: switch.front_door_sensor
    service: switch.turn_off
- id: '1529366648322'
  alias: Open chicken pop hole door at dawn
  trigger:
  - event: sunrise
    offset: -00:30:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: cover.chicken_coop_door
    service: cover.open_cover
- id: '1541895123590'
  alias: Garage CCTV Offline
  trigger:
  - entity_id: binary_sensor.garage_cctv_online
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Garage CCTV Offline
    service: notify.google_cloud_notify
- id: '1541895123591'
  alias: Drive CCTV Offline
  trigger:
  - entity_id: binary_sensor.drive_cctv_online
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Drive CCTV Offline
    service: notify.google_cloud_notify
- id: '1541895123592'
  alias: Door CCTV Offline
  trigger:
  - entity_id: binary_sensor.front_door_cctv_online
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Front Door CCTV Offline
    service: notify.google_cloud_notify
- id: '1544967364329'
  alias: Battery Low tradfri_remote_control
  trigger:
  - below: '20'
    entity_id: sensor.tradfri_remote_control
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Sitting room Tradfri remote battery low. Currently {{ states.sensor.tradfri_remote_control.state
        }}%
    service: notify.google_cloud_notify
- id: '1544967729500'
  alias: Battery Low tradfri_wireless_dimmer
  trigger:
  - below: '25'
    entity_id: sensor.tradfri_wireless_dimmer
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Master bedroom Tradfri remote battery low. Currently {{ states.sensor.tradfri_wireless_dimmer.state
        }}%
    service: notify.google_cloud_notify
- id: '1557360744014'
  alias: Increment TOR DB Disconnect Automation
  trigger:
  - entity_id: binary_sensor.tor_db_status
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: counter.tor_db_disconnect_counter
    service: counter.increment
