- id: '1529279555355'
  alias: Reset Front Door Sensor
  trigger:
  - entity_id: switch.front_door_sensor
    from: 'off'
    platform: state
    to: 'on'
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: 00:00:05
  - data:
      entity_id: switch.front_door_sensor
    service: switch.turn_off
- id: '1529366648322'
  alias: Open chicken pop hole door at dawn
  trigger:
  - event: sunrise
    offset: -00:30:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: cover.chicken_coop_door
    service: cover.open_cover
- id: '1541895123590'
  alias: Garage CCTV Offline
  trigger:
  - entity_id: binary_sensor.garage_cctv_online
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Garage CCTV Offline
    service: notify.google_cloud_notify
- id: '1541895123591'
  alias: Drive CCTV Offline
  trigger:
  - entity_id: binary_sensor.drive_cctv_online
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Drive CCTV Offline
    service: notify.google_cloud_notify
- id: '1541895123592'
  alias: Door CCTV Offline
  trigger:
  - entity_id: binary_sensor.front_door_cctv_online
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Front Door CCTV Offline
    service: notify.google_cloud_notify
- id: '1544967364329'
  alias: Battery Low tradfri_remote_control
  trigger:
  - below: '20'
    entity_id: sensor.tradfri_remote_control
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Sitting room Tradfri remote battery low. Currently {{ states.sensor.tradfri_remote_control.state
        }}%
    service: notify.google_cloud_notify
- id: '1544967729500'
  alias: Battery Low tradfri_wireless_dimmer
  trigger:
  - below: '25'
    entity_id: sensor.tradfri_wireless_dimmer
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Master bedroom Tradfri remote battery low. Currently {{ states.sensor.tradfri_wireless_dimmer.state
        }}%
    service: notify.google_cloud_notify
- id: '1557360744014'
  alias: Increment TOR DB Disconnect Automation
  trigger:
  - entity_id: binary_sensor.tor_db_status
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: counter.tor_db_disconnect_counter
    service: counter.increment
- id: '1558317969078'
  alias: CCTV Reboot Each Day
  trigger:
  - at: 06:45
    platform: time
  condition: []
  action:
  - service: rest_command.cctv_front_door_restart
  - delay: 00:10
  - service: rest_command.cctv_drive_restart
  - delay: 00:10
  - service: rest_command.cctv_garage_restart
  - delay: 00:10
  - service: rest_command.cctv_garage2_restart
- id: '1564192629041'
  alias: Pot Irrigation Script Off to Valve Off
  trigger:
  - entity_id: script.pot_irrigation_timer
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.pot_irrigation_valve
    service: switch.turn_off
- id: '1564192623451'
  alias: Irrigate Pots at Sunrise
  trigger:
  - platform: template
    value_template: '{{states.sensor.time.state == states.sensor.irrigation_starttime.state}}'
  condition:
  - condition: template
    value_template: '{{states.sensor.pot_irrigation_next_run.state[5:15] == now().date().strftime(''%d-%m-%Y'')}}'
  - condition: state
    entity_id: sensor.pots_irrigation_interlock
    state: No Problem
  action:
  - entity_id: script.pot_irrigation_timer
    service: script.pot_irrigation_timer
- id: '1564192623452'
  alias: Irrigate Lawn at Sunrise
  trigger:
  - platform: template
    value_template: '{{states.sensor.time.state == states.sensor.irrigation_starttime.state}}'
  condition:
  - condition: template
    value_template: '{{states.sensor.lawn_irrigation_next_run.state[5:15] == now().date().strftime(''%d-%m-%Y'')}}'
  - condition: state
    entity_id: sensor.lawn_irrigation_interlock
    state: No Problem
  action:
  - entity_id: script.lawn_irrigation_timer
    service: script.lawn_irrigation_timer
- id: '1564234217905'
  alias: Lawn Irrigation Script Off to Valve Off
  trigger:
  - entity_id: script.lawn_irrigation_timer
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.lawn_irrigation_valve
    service: switch.turn_off
