homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data
  elevation: !secret elevation
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  customize: !include includes\customise.yaml


# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  server_port: 443
  ssl_certificate: !secret SSL_cert
  ssl_key:  !secret SSL_key
  base_url: !secret Base_url
#  ip_ban_enabled: True
#  login_attempts_threshold: 20
  trusted_networks:
  - 127.0.0.1
  - 192.168.0.0/24
  - !secret myip
  #- ::1

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# recorder:
#   purge_days: 24
#   # exclude:

# View all events in a logbook
logbook:
   exclude:
    entities:
      - binary_sensor.bunny_shed_heater
      - sensor.dark_sky_summary
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_daily_summary

# https://github.com/home-assistant/home-assistant/issues/1806
logger:
  default: warning
  logs:
    requests.packages.urllib3.connectionpool: critical

# Track the sun
sun:
  elevation: !secret elevation



############################################################
#
# Components
#
############################################################


# APC UPS
apcupsd:
  host: localhost
  port: 3551

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

climate:
  platform: nest


# media_player:
#  # - platform: plex
#  - platform: cast

notify:
  - platform: pushover
    name: Pushover Notify
    api_key:  !secret pushover_api_key
    user_key:  !secret pushover_user_key

  - platform: html5
    name: Google Cloud Notify
    gcm_api_key: !secret gcmKey
    gcm_sender_id: !secret gcmID

  # - name: Facebook Notify
  #   platform: facebook
  #   page_access_token: !secret FB_Key

device_tracker:
  platform: owntracks
  max_gps_accuracy: 250

mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password

# Text to speech
tts:
  platform: google

ifttt:
  key: !secret ifttt_key



rflink:
  host: !secret RF_Link_IP
  port: !secret RF_Link_Port
  wait_for_ack: True
  reconnect_interval: 1 #1 second

############################################################
#
# Includes
# Merge named https://home-assistant.io/docs/configuration/splitting_configuration/
#
############################################################

# Merge List
automation: !include_dir_merge_list includes\automation
sensor: !include_dir_merge_list includes\sensors
light: !include_dir_merge_list includes\lights
binary_sensor: !include_dir_merge_list includes\binary_sensors\
switch: !include_dir_merge_list includes\switch

# Merge named
script: !include_dir_merge_named includes\scripts


# Single Files
zone: !include includes\zone.yaml
camera: !include includes\cameras.yaml


# Merge Named
group: !include includes\group\groups.yaml
input_slider: !include includes\input_slider.yaml





input_boolean:
  task_heat_towel_rail:
    name: Heat the towel rail for 1 hour
    initial: off
    icon: mdi:temperature-celsius


weblink:
  entities:
    - name: Router
      url: !secret RouterIP
      icon: mdi:router-wireless

    - name: uTorrent
      url: !secret uTorrentIP
      icon: mdi:download

    - name: SickRage
      url: !secret SickRageIP
      icon: mdi:monitor

    - name: CouchPotato
      url: !secret CouchPotatoIP
      icon: mdi:filmstrip

    - name: Server Glances
      url: !secret server_glancesIP
      icon: mdi:format-list-bulleted

#NOT WORKING!
alexa:
  intents:
    LocateIntent:
      action:
        service: notify.notify
        data_template:
          message: "The location of {{ User }} has been queried via Alexa."
          data:
            title: "Home Assistant"
            sound: falling
            device: pixel
            url: !secret web_address
      speech:
        type: plaintext
        text: >
          {%- for state in states.device_tracker -%}
            {%- if state.name.lower() == User.lower() -%}
              {{ state.name }} is currently at {{ state.state }}
            {%- endif -%}
          {%- else -%}
            I am sorry, I do not know where {{ User }} is.
          {%- endfor -%}
      card:
        type: simple
        title: Sample title
        content: Some more content

  #       alexa:
  # intents:
  #   LocateIntent:
  #     action:
  #       service: notify.notify
  #       data_template:
  #         message: The location of {{ User }} has been queried via Alexa.
  #     speech:
  #       type: plaintext
  #       text: >
  #         {%- for state in states.device_tracker -%}
  #           {%- if state.name.lower() == User.lower() -%}
  #             {{ state.name }} is at {{ state.state }}
  #           {%- endif -%}
  #         {%- else -%}
  #           I am sorry, I do not know where {{ User }} is.
  #         {%- endfor -%}
  #     card:
  #       type: simple
  #       title: Sample title
  #       content: Some more content



#NOT WORKING!
apiai:
  intents:
    GetTemperature:
      speech: The temperature at home is {{ states.sensor.kitchen_temperature.state }} degrees
      async_action: False
      # action:
      #   service: notify.notify
      #   data_template:
      #     message: Api.ai has send a request
