#######################################
# Home-Assistant-Configuration
# https://github.com/genestealer/Home-Assistant-Configuration
# See Readme for info: https://github.com/genestealer/Home-Assistant-Configuration/blob/master/README.md
#######################################

############################################################
#
# Homeassistant Configuration
#
############################################################
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data
  elevation: !secret elevation
  external_url: !secret Base_url
  internal_url: !secret internal_ip
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization file
  customize: !include customize.yaml
  #Unhide the push notifcation slider https://github.com/home-assistant/home-assistant/issues/16043
  auth_providers:
   - type: homeassistant
   # uncomment this to enable backwards compatible API password support
   # - type: legacy_api_password
  # whitelist_external_dirs:
  #   - /www
  #   - /tmp
  # packages: 
  #   garden: !include_dir_merge_named packages/garden
  packages: !include_dir_named packages/
  # packages: !include_dir_merge_named packages/


############################################################
#
# Standard Configuration Elements
#
############################################################

# Enables the frontend
frontend:

# https://github.com/thomasloven/hass-browser_mod
browser_mod:

# https://github.com/thomasloven/hass-lovelace_gen
lovelace_gen:

lovelace:
  mode: storage
  resources:
    # - url: browser_mod.js
    #   type: js
    - url: /browser_mod.js
      type: module
    - url: browser_mod.js
      type: module
    - url: /local/community/lovelace-card-mod/card-mod.js
      type: module
    - url: /local/community/lovelace-hui-element/hui-element.js
      type: module
    - url: /local/community/button-card/button-card.js
      type: module
    - url: /local/community/config-template-card/config-template-card.js
      type: module
    - url: /local/community/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /local/community/lovelace-layout-card/layout-card.js
      type: module
    - url: /local/community/lovelace-state-switch/state-switch.js
      type: module
    - url: /local/community/lovelace-time-picker-card/time-picker-card.js
      type: module
    # - url: /local/community/lovelace-multiple-entity-row/multiple-entity-row.js
    #   type: module
    # - url: /local/community/stack-in-card/stack-in-card.js
    #   type: module
  # Add yaml dashboards
  dashboards:
    lovelace-garden:
      mode: yaml
      title: Garden
      icon: mdi:script
      show_in_sidebar: true
      filename: myirrigation.yaml
# Enables configuration UI
config:

scene: !include scenes.yaml

#Home Assistant Cloud - NOPE!
cloud:

# Enable web interface
http:
#  api_password: !secret http_password
  server_port: 8123
  # SSL is now performed by Apache reverse proxy
  #  ssl_certificate: !secret SSL_cert
  #  ssl_key: !secret SSL_key
  # base_url: !secret Base_url # removed in rev 0.110
  ip_ban_enabled: False
  login_attempts_threshold: 20
  #use_x_forwarded_for: True
  #trusted_proxies:
  #- 192.168.1.28

#  trusted_networks:
#  - 127.0.0.1
#  - 192.168.0.0/24
#  - 172.17.0.0/16 # Docker bridge
#  - 172.30.32.0/23 # Docker hassio
  # 172.0.0.1 trust docker internal network from addons. https://github.com/home-assistant/home-assistant/issues/15873
  # - !secret myip
  #- ::1

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time. (Cleared at startup)
history:
   exclude:
    entities:
      - sensor.server_server_health
      # - sensor.pi_hole_ads_blocked_today
      # - sensor.pi_hole_ads_percentage_blocked_today
      # - sensor.pi_hole_dns_queries_today
      - sensor.date_time
      - sensor.time
      - sensor.unscaled_house_consumption_current
      - sensor.server_server_power_on_time


# View all events in a logbook
logbook:
   exclude:
    entities:
      - sensor.server_server_health
      # - sensor.pi_hole_ads_blocked_today
      # - sensor.pi_hole_ads_percentage_blocked_today
      # - sensor.pi_hole_dns_queries_today
      - sensor.date_time
      - sensor.time
      - sensor.unscaled_house_consumption_current
      - sensor.server_server_power_on_time
      - sensor.cc_cpu_temperature
      - sensor.cc_cpu_load

# Tracked history is kept for 12 days. (Not cleared at startup)
recorder:
  purge_keep_days: 24
  #db_url: !secret mariadb_db_url
  exclude:
    # domains:
    #   - automation
    #   - updater
    entities:
      - binary_sensor.cctv_garden_p3354_vmd3_0
      - binary_sensor.cctv_garden_p3354_vmd4_camera1profileany
      - binary_sensor.cctv_garden_p3354_vmd4_camera1profile1
      - binary_sensor.cctv_garden_p3354_vmd3_0
      - binary_sensor.cctv_garden_p3354_vmd3_0
      - binary_sensor.cctv_garden_p3354_vmd3_0
      # - binary_sensor.binary_sensor.p3364_l_0_vmd3_0
      # - binary_sensor.p3364_l_0_vmd4_camera1profileany
      # - binary_sensor.p3364_l_0_vmd4_camera1profile1
      # - sensor.cpu_temperature


# Enables a map showing the location of tracked devices
map:

# https://github.com/home-assistant/home-assistant/issues/1806
logger:
  default: fatal
  logs:
    requests.packages.urllib3.connectionpool: critical
    rflink.protocol: fatal
    homeassistant.components.sensor.plex: fatal
    urllib3.connectionpool: error


system_health:

default_config:

############################################################
#
# Components
#
############################################################

# Track the sun.
sun:
  elevation: !secret elevation

# Text to speech.
tts:
  - platform: google_translate
    service_name: google_say

# Use external MQTT broker.
mqtt:
  broker: !secret mqtt_broker
  port: 1883
  client_id: home-assistant
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true

# Push notification providers.
notify:
  - name: Google Cloud Notify
    platform: html5
    # gcm_api_key: !secret gcmKey
    # gcm_sender_id: !secret gcmID
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email

  - platform: pushover
    name: Pushover Notify
    api_key:  !secret pushover_api_key
    user_key:  !secret pushover_user_key

  - platform: pushover
    name: Pushover Notify Doorbell
    api_key:  !secret pushover_api_key_doorbell
    user_key:  !secret pushover_user_key
  # - name: Facebook Notify
  #   platform: facebook
  #   page_access_token: !secret FB_Key


# APC UPS Network Infomation Server, which talks to the networked UPS via apcupsd daemon (outside of HASS, but on same system).
apcupsd:
  host: a722577e-apcupsd-net
#  host: !secret apcupsdNisIP
#  port: !secret apcupsdNisPort

#Google Nest integration.
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
climate:
  - platform: nest
  # - platform: generic_thermostat
  #   name: Bunny Shed Thermostat


# Device trackers.
device_tracker:
  # - platform: owntracks
  #   max_gps_accuracy: 250
  - platform: google_maps # Elements per day’ to a limit of 645.
    username: !secret google_maps_username

# Moved to integrations UI from Rev 0.112
  # - platform: tile
  #   username: !secret tile_username
  #   password: !secret tile_password

    # password: !secret google_maps_password
  # - platform: googlehome
  #   host: !secret google_home_hub_ip

  # - platform: ping
  #   hosts:
  #     hostone: 192.168.1.16
  # - platform: snmp
  #   host: 192.168.1.1
  #   community: public
  #   baseoid: 1.3.6.1.2.1.2.2

# IFTT integration.
ifttt:
  key: !secret ifttt_key

# RFLink gateway integration, via ethernet bridge.
rflink:
  host: !secret RF_Link_IP
  port: !secret RF_Link_Port
  wait_for_ack: True
  reconnect_interval: 5 #1 second
  ignore_devices:
    - owl_cm113_ead1_current3
    - owl_cm113_ead1_current1
    # - sensor.owl_cm113_ea7f_current2
    # - sensor.owl_cm113_ea7f_current3
    # - sensor.owl_cm113_ea9f_current2
    # - sensor.owl_cm113_ea9f_current3
    # - sensor.owl_cm130_007f_kwatt

    # - sensor.alectov5_*
    # - sensor.v2phoenix_*
    # - sensor.dkw2012_*
    # - light.drayton_*
    # - light.elrodb_*
    # - light.mertik_*
    # - light.drayton_*
    # - light.btf_*
    # - light.v2phoenix*


#Ikea Tradfri ethernet gatway integration.
tradfri:
  host: !secret Ikea_Tradfri_IP
  allow_tradfri_groups: true
  # api_key: !secret Ikea_Tradfri_KEY

# # Pi Hole integration sensor
# pi_hole:
#   host: !secret piHoleIPandPort

# Amazon Alexa integration via emulated Philips hue.
emulated_hue:
  host_ip: !secret Local_Host
  # listen_port: 8300
  entities:
    light.kitchen_under_counter_lights:
      name: "Kitchen Lights"

# Side panel frames, but only externally accessible URLs work.
panel_iframe:
  webmin1:
    title: StormBreaker Webmin
    icon: mdi:gauge
    url: !secret panel_iframe_StormBreaker_Webmin_URL
  downloads:
    title: Downloads
    icon: mdi:briefcase-download
    url: !secret panel_iframe_Downloads_URL
  sonarr:
    title: Sonarr
    icon: mdi:youtube-tv
    url: !secret panel_iframe_Sonarr_URL
  radarr:
    title: Radaar
    icon: mdi:filmstrip
    url: !secret panel_iframe_Radarr_URL
  subsonic:
    title: Subsonic
    icon: mdi:library-music
    url: !secret panel_iframe_Subsonic_URL
    # mdi:mdi-audiobook
    # webmin2:
    #   title: Thor Webmin
    #   icon: mdi:gauge
    #   url: !secret panel_iframe_Thor_Webmin_URL


# Google Assistant intergration.
# Every now and again have to visit this link and lick TEST: https://console.actions.google.com/project/hassio-214617/accountlinking/
google_assistant:
  project_id: !secret google_assistant_project_id
  # api_key: !secret google_assistant_api_key # deprecated and will be removed in 0.105
  service_account: !include private/Home_Assistant-78aa4d65f173.json
  report_state: true
  # # exposed_domains:
  # #   - switch
  # #   - light
  # expose_by_default: false

  # exposed_domains:
  #   - switch
  #   - light

  entity_config:
    climate.entryway:
      expose: false
    media_player.kitchen_and_bedroom:
      expose: false
    media_player.googlehomehub2078:
      expose: false
    media_player.bedroom_display:
      expose: false
    media_player.kitchen_stereo:
      expose: false
    media_player.kitchen_tv:
      expose: false
    media_player.googlehome2495:
      expose: false
    media_player.office_display:
      expose: false
    media_player.chromecast7797:
      expose: false
    media_player.living_room_tv:
      expose: false
    media_player.googlehome2900:
      expose: false
    media_player.googlehomehub5970:
      expose: false
    media_player.garage:
      expose: false
    media_player.guest_bedroom:
      expose: false
    group.all_automations:
      expose: false # Hide this to avoid telling Google Assistant to shut down everything, it disabling all automations.
    group.all_covers:
      expose: false
    group.all_lights:
      expose: false
    group.all_switchs:
      expose: false
    group.all_scripts:
      expose: false
    group.automation_system_view:
      expose: false
    group.bathroom_towel_rail_group:
      expose: false
    group.bathroom_view:
      expose: false
    group.bedroom_guest:
      expose: false
    group.bedroom_master:
      expose: false
    group.bunny_shed_controller_info_group:
      expose: false
    group.bunny_shed_group:
      expose: false
    group.bunny_shed_settings:
      expose: false
    group.bunny_shed_view:
      expose: false
    group.rf_link_group:
      expose: false
    group.server_ilo_status_group:
      expose: false


    group.groups:
      expose: false
    group.media_players:
      expose: false
    group.media_player:
      expose: false
    light.bedroom:
      expose: false

  # Not needed since release 0.80
  # client_id: !secret google_assistant_client_id
  # access_token: !secret google_assistant_access_token

# # Unused Axis CCTV intergration.
# axis:
#    p3301:
#      host: !secret axis_front_door_IP
#      username: !secret axis_front_door_username
#      password: !secret axis_front_door_password
#      include:
#       # - camera
#       # - motion
#       # - vmd3
#       # - sound
#      trigger_time: 0

# Internet Speed Test
speedtestdotnet:
  monitored_conditions:
   - ping
   - download
   - upload

# Number counter
counter:
  tor_db_disconnect_counter:
    name: TOR DB Disconnections
    initial: 0
    step: 1

# Proxy video live streams through Home Assistant
stream:


weather:
  - platform: darksky
    api_key: !secret dark_sky_key
    mode: daily
    # forecast:
    #   - 0
    # monitored_conditions:
    #   - temperature_high           
    #   - minutely_summary 

utility_meter:
  energy_cumulative_month:
    source: sensor.house_power_meter
    cycle: monthly
    # tariffs:
    #   - 
  energy_cumulative_daily:
    source: sensor.house_power_meter
    cycle: daily

############################################################
#
# Includes
# Merge named https://home-assistant.io/docs/configuration/splitting_configuration/
#
############################################################

# Single Files
zone: !include includes/zone.yaml
shell_command: !include includes/shell_commands.yaml
automation: !include automations.yaml # Cannot change location or filename as the automations editors only creates here!
script: !include scripts.yaml

# Merge List
automation old: !include_dir_merge_list includes/automation
sensor: !include_dir_merge_list includes/sensors
light: !include_dir_merge_list includes/lights
binary_sensor: !include_dir_merge_list includes/binary_sensors
switch: !include_dir_merge_list includes/switch
cover: !include_dir_merge_list includes/cover
camera: !include_dir_merge_list includes/cameras

# Merge named dir
# script: !include_dir_merge_named includes/scripts
input_boolean: !include_dir_merge_named includes/input_boolean
input_select: !include_dir_merge_named includes/input_select
input_number: !include_dir_merge_named includes/input_number
rest_command: !include_dir_merge_named includes/rest_commands


# Merge Named
group: !include includes/groups.yaml


# Plex Sensor
# plex:
#   host: !secret plex_server_host
#   token: !secret plex_server_key



# weblink:
#   entities:
#     - name: Router
#       url: !secret RouterIP
#       icon: mdi:router-wireless
#
#     - name: uTorrent
#       url: !secret uTorrentIP
#       icon: mdi:download
#
#     - name: SickRage
#       url: !secret SickRageIP
#       icon: mdi:monitor
#
#     - name: CouchPotato
#       url: !secret CouchPotatoIP
#       icon: mdi:filmstrip
#
#     - name: Server Glances
#       url: !secret server_glancesIP
#       icon: mdi:format-list-bulleted



# #NOT WORKING!
# alexa:
#   intents:
#     LocateIntent:
#       action:
#         service: notify.notify
#         data_template:
#           message: "The location of {{ User }} has been queried via Alexa."
#           data:
#             title: "Home Assistant"
#             sound: falling
#             device: pixel
#             url: !secret web_address
#       speech:
#         type: plaintext
#         text: >
#           {%- for state in states.device_tracker -%}
#             {%- if state.name.lower() == User.lower() -%}
#               {{ state.name }} is currently at {{ state.state }}
#             {%- endif -%}
#           {%- else -%}
#             I am sorry, I do not know where {{ User }} is.
#           {%- endfor -%}
#       card:
#         type: simple
#         title: Sample title
#         content: Some more content

  #       alexa:
  # intents:
  #   LocateIntent:
  #     action:
  #       service: notify.notify
  #       data_template:
  #         message: The location of {{ User }} has been queried via Alexa.
  #     speech:
  #       type: plaintext
  #       text: >
  #         {%- for state in states.device_tracker -%}
  #           {%- if state.name.lower() == User.lower() -%}
  #             {{ state.name }} is at {{ state.state }}
  #           {%- endif -%}
  #         {%- else -%}
  #           I am sorry, I do not know where {{ User }} is.
  #         {%- endfor -%}
  #     card:
  #       type: simple
  #       title: Sample title
  #       content: Some more content


#
# #NOT WORKING!
# api:
#   intents:
#     GetTemperature:
#       speech: The temperature at home is {{ states.sensor.kitchen_temperature.state }} degrees
#       async_action: False
#       # action:
#       #   service: notify.notify
#       #   data_template:
#       #     message: Api.ai has send a request


# https://github.com/kloggy/HA-Irrigation-Version2/blob/master/prerequisites.yaml
input_text:
  notifications_user1_name:
    min: 0
    max: 20
  notifications_user2_name:
    min: 0
    max: 20