############################################################
#
# Home Assistant Main Configuration File
#
############################################################

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data
  elevation: !secret elevation
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  customize: !include includes\customise.yaml

    
# View all events in a logbook
logbook:

# Enables support for tracking state changes over time.
history:

# Show links to resources in log and frontend
#introduction:

# Checks for available updates
updater:

# Password
http:
  api_password: !secret http_password
  #ssl_certificate: C:\Cert\server.richardhuish.com.crt
  #ssl_key: C:\Cert\server.richardhuish.com.key

recorder:
  purge_days: 365

# Track the sun
sun:
  elevation: !secret elevation

# Allows you to issue voice commands from the frontend
conversation:

# Enables the frontend
frontend:  

# Discover some devices automatically
discovery:


############################################################
#
# Components
#
############################################################


# APC UPS
apcupsd:
  host: localhost
  port: 3551

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

climate:
  platform: nest


media_player:
 - platform: plex
 - platform: cast

notify:
- platform: pushover
  api_key:  !secret pushover_api_key
  user_key:  !secret pushover_user_key

device_tracker:
  platform: owntracks
  max_gps_accuracy: 250

mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password 
    
tts:
  - platform: google

ifttt:
  key: !secret ifttt_key 

emulated_hue:
  # type: alexa
  # host_ip: 192.168.1.20
  # listen_port: 8300


############################################################
#
# Includes
#
############################################################

# Merge List
automation: !include_dir_merge_list includes/automation 
sensor: !include_dir_merge_list includes/sensors

script: !include_dir_merge_named includes/scripts

# Single Files
zone: !include includes/zone.yaml
#camera: !include includes/cameras.yaml
binary_sensor: !include includes/binary_sensors.yaml
light: !include includes\light.yaml

# Merge Named
group: !include_dir_merge_named includes/group



input_slider:
  minute_delay:
    name: Heat for x Mins
    initial: 60
    min: 1
    max: 120
    step: 1
    icon: mdi:clock-end  
  shed_target_temp:
    name: Bunny Shed Target Temperature Slider
    min: 1
    max: 15
    step: 1
    unit_of_measurement: step  
    icon: mdi:target



input_boolean:
  task_heat_towel_rail:
    name: Heat the towel rail for 1 hour
    initial: off
    icon: mdi:temperature-celsius
   
 

#automation:
#  alias: Heat Towel Rail
#  trigger:
#    platform: state
#    entity_id: input_boolean.task_heat_towel_rail
#    to: 'on'
#  condition:
#    platform: state
#    entity_id: input_boolean.task_heat_towel_rail
#    state: 'on'
#  action:
#    service: climate.set_temperature
#    data:
#      temperature: 26
#      entity_id: climate.hallway      
