#######################################
# Home-Assistant-Configuration
# https://github.com/genestealer/Home-Assistant-Configuration
# See Readme for info: https://github.com/genestealer/Home-Assistant-Configuration/blob/master/README.md
#######################################

############################################################
#
# Homeassistant Configuration
#
############################################################
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data
  elevation: !secret elevation
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization file
  customize: !include customize.yaml
  #Unhide the push notifcation slider https://github.com/home-assistant/home-assistant/issues/16043
  auth_providers:
   - type: homeassistant
   # uncomment this to enable backwards compatible API password support
   # - type: legacy_api_password

############################################################
#
# Standard Configuration Elements
#
############################################################

# Enables the frontend
frontend:

# Enables configuration UI
config:

#Home Assistant Cloud - NOPE!
#cloud:

# Enable web interface
http:
  api_password: !secret http_password
  server_port: 8123
  # SSL is now performed by Apache reverse proxy
  #  ssl_certificate: !secret SSL_cert
  #  ssl_key: !secret SSL_key
  base_url: !secret Base_url
  ip_ban_enabled: False
  login_attempts_threshold: 20
  #use_x_forwarded_for: True
  #trusted_proxies:
  #- 192.168.1.28

  trusted_networks:
  - 127.0.0.1
  - 192.168.0.0/24
  - 172.17.0.0/16 # Docker bridge
  - 172.30.32.0/23 # Docker hassio
  # 172.0.0.1 trust docker internal network from addons. https://github.com/home-assistant/home-assistant/issues/15873
  # - !secret myip
  #- ::1

# Checks for available updates
updater:

# Discover some devices automatically
discovery:
  ignore:
    - roku

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time. (Cleared at startup)
history:

# Tracked history is kept for 12 days. (Not cleared at startup)
recorder:
  purge_keep_days: 12

# View all events in a logbook
logbook:
   exclude:
    entities:
      - sensor.dark_sky_summary
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_daily_summary
      - sensor.server_server_health
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_blocked_today
      - sensor.pihole_dns_queries_today

# Enables a map showing the location of tracked devices
map:

# https://github.com/home-assistant/home-assistant/issues/1806
logger:
  default: debug
  logs:
    requests.packages.urllib3.connectionpool: critical
    rflink.protocol: fatal
    homeassistant.components.sensor.plex: fatal
    urllib3.connectionpool: error



############################################################
#
# Components
#
############################################################

# Track the sun.
sun:
  elevation: !secret elevation

# Text to speech.
tts:
  - platform: google

# Use external MQTT broker.
mqtt:
  broker: !secret mqtt_broker
  port: 1883
  client_id: home-assistant
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password

# Push notification providers.
notify:
    - name: Google Cloud Notify
      platform: html5
      gcm_api_key: !secret gcmKey
      gcm_sender_id: !secret gcmID
  # - platform: pushover
  #   name: Pushover Notify
  #   api_key:  !secret pushover_api_key
  #   user_key:  !secret pushover_user_key

  # - name: Facebook Notify
  #   platform: facebook
  #   page_access_token: !secret FB_Key


# APC UPS Network Infomation Server, which talks to the networked UPS via apcupsd daemon (outside of HASS, but on same system).
apcupsd:
  host: a722577e-apcupsd-net
#  host: !secret apcupsdNisIP
#  port: !secret apcupsdNisPort

# Google Nest integration.
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
climate:
  platform: nest

# Device trackers.
device_tracker:
  - platform: owntracks
    max_gps_accuracy: 250
  - platform: google_maps
    username: google_maps_username
    password: google_maps_password
  - platform: googlehome
    host: !secret google_home_hub_ip
    
  # - platform: ping
  #   hosts:
  #     hostone: 192.168.1.16
  # - platform: snmp
  #   host: 192.168.1.1
  #   community: public
  #   baseoid: 1.3.6.1.2.1.2.2

# IFTT integration.
ifttt:
  key: !secret ifttt_key

# RFLink gateway integration, via ethernet bridge.
rflink:
  host: !secret RF_Link_IP
  port: !secret RF_Link_Port
  wait_for_ack: True
  reconnect_interval: 1 #1 second
  ignore_devices:
    - sensor.owl_cm113_ea7f_current2
    - sensor.owl_cm113_ea7f_current3
    - sensor.owl_cm113_ea9f_current2
    - sensor.owl_cm113_ea9f_current3
    - sensor.owl_cm130_007f_kwatt
    - sensor.alectov5_*
    # - sensor.alectov5_000d_raintot
    # - sensor.blyss_th_0004_hum
    # - sensor.blyss_th_0004_hum
    # - sensor.blyss_th_0004_temp
    # - sensor.blyss_th_2000_hum
    # - sensor.blyss_th_2000_temp
    # - sensor.blyss_th_9000_hum
    # - sensor.blyss_th_9000_temp
    # - sensor.blyss_th_a880_hum
    # - sensor.blyss_th_a880_temp
    - sensor.dkw2012_*
    # - sensor.dkw2012_0040_bat
    # - sensor.dkw2012_0040_hum
    # - sensor.dkw2012_0040_raintot
    # - sensor.dkw2012_0040_temp
    # - sensor.dkw2012_0040_windir
    # - sensor.dkw2012_0040_wings
    # - sensor.dkw2012_0040_winsp
    - light.drayton_1180_*
    - elrodb_72fab739_*
    - mertik_44_*
    - drayton_1180_*


#Ikea Tradfri ethernet gatway integration.
tradfri:
  host: !secret Ikea_Tradfri_IP
  allow_tradfri_groups: true
  # api_key: !secret Ikea_Tradfri_KEY

# Amazon Alexa integration via emulated Philips hue.
emulated_hue:
  host_ip: !secret Local_Host
  # listen_port: 8300
  entities:
    light.kitchen_under_counter_lights:
      name: "Kitchen Lights"

# Side panel frames, but only externally accessible URLs work.
panel_iframe:
  ide:
    title: IDE
    icon: mdi:code-braces
    url: !secret panel_iframe_IDE_URL
  octobox:
    title: Portainer
    icon: mdi:docker
    url: !secret panel_iframe_Portainer_URL
  webmin1:
    title: StormBreaker Webmin
    icon: mdi:gauge
    url: !secret panel_iframe_StormBreaker_Webmin_URL
  webmin2:
    title: Thor Webmin
    icon: mdi:gauge
    url: !secret panel_iframe_Thor_Webmin_URL

# Google Assistant intergration.
google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_api_key
  # Not needed since release 0.80
  # client_id: !secret google_assistant_client_id
  # access_token: !secret google_assistant_access_token

# # Unused Axis CCTV intergration.
# axis:
#    p3301:
#      host: !secret axis_front_door_IP
#      username: !secret axis_front_door_username
#      password: !secret axis_front_door_password
#      include:
#       # - camera
#       # - motion
#       # - vmd3
#       # - sound
#      trigger_time: 0

############################################################
#
# Includes
# Merge named https://home-assistant.io/docs/configuration/splitting_configuration/
#
############################################################

# Single Files
zone: !include includes/zone.yaml
camera: !include includes/cameras.yaml
shell_command: !include includes/shell_commands.yaml
automation: !include automations.yaml # Cannot change location or filename as the automations editors only creates here!

# Merge List
automation old: !include_dir_merge_list includes/automation
sensor: !include_dir_merge_list includes/sensors
light: !include_dir_merge_list includes/lights
binary_sensor: !include_dir_merge_list includes/binary_sensors
switch: !include_dir_merge_list includes/switch
cover: !include_dir_merge_list includes/cover

# Merge named dir
script: !include_dir_merge_named includes/scripts
input_boolean: !include_dir_merge_named includes/input_boolean
input_select: !include_dir_merge_named includes/input_select
input_number: !include_dir_merge_named includes/input_number

# Merge Named
group: !include includes/group/groups.yaml






# media_player:
#  # - platform: plex
#  - platform: cast



# weblink:
#   entities:
#     - name: Router
#       url: !secret RouterIP
#       icon: mdi:router-wireless
#
#     - name: uTorrent
#       url: !secret uTorrentIP
#       icon: mdi:download
#
#     - name: SickRage
#       url: !secret SickRageIP
#       icon: mdi:monitor
#
#     - name: CouchPotato
#       url: !secret CouchPotatoIP
#       icon: mdi:filmstrip
#
#     - name: Server Glances
#       url: !secret server_glancesIP
#       icon: mdi:format-list-bulleted



# #NOT WORKING!
# alexa:
#   intents:
#     LocateIntent:
#       action:
#         service: notify.notify
#         data_template:
#           message: "The location of {{ User }} has been queried via Alexa."
#           data:
#             title: "Home Assistant"
#             sound: falling
#             device: pixel
#             url: !secret web_address
#       speech:
#         type: plaintext
#         text: >
#           {%- for state in states.device_tracker -%}
#             {%- if state.name.lower() == User.lower() -%}
#               {{ state.name }} is currently at {{ state.state }}
#             {%- endif -%}
#           {%- else -%}
#             I am sorry, I do not know where {{ User }} is.
#           {%- endfor -%}
#       card:
#         type: simple
#         title: Sample title
#         content: Some more content

  #       alexa:
  # intents:
  #   LocateIntent:
  #     action:
  #       service: notify.notify
  #       data_template:
  #         message: The location of {{ User }} has been queried via Alexa.
  #     speech:
  #       type: plaintext
  #       text: >
  #         {%- for state in states.device_tracker -%}
  #           {%- if state.name.lower() == User.lower() -%}
  #             {{ state.name }} is at {{ state.state }}
  #           {%- endif -%}
  #         {%- else -%}
  #           I am sorry, I do not know where {{ User }} is.
  #         {%- endfor -%}
  #     card:
  #       type: simple
  #       title: Sample title
  #       content: Some more content


#
# #NOT WORKING!
# api:
#   intents:
#     GetTemperature:
#       speech: The temperature at home is {{ states.sensor.kitchen_temperature.state }} degrees
#       async_action: False
#       # action:
#       #   service: notify.notify
#       #   data_template:
#       #     message: Api.ai has send a request
