####################################################
# Binary Sensors
####################################################

binary_sensor:
  # Sun2 Sensor https://github.com/pnbruckner/ha-sun2
  # For https://github.com/kloggy/HA-Irrigation-Version2/blob/master/Pre-Requisites.md
  - platform: sun2
    monitored_conditions:
      - elevation

  - platform: trend
    sensors:
      local_rainfall_trend:
        friendly_name: Local Rainfall Trend
        entity_id: sensor.local_total_rain
        max_samples: 2

####################################################
# New style Template sensors
####################################################
template:
  # - sensor:
  #     # ...
  - binary_sensor:
      # Used by kloggy/HA-Irrigation-Version2
      - name: Raining Now
        state: "{{ is_state('sensor.openweathermap_precipitation_kind', 'Rain') }}"

  #  Track if an irrigation Controllers goes offline. Used in the alert and kloggy/HA-Irrigation-Version2
  - binary_sensor:
      # https://github.com/kloggy/HA-Irrigation-Version2
      - name: Irrigation Controllers Online
        state: "{{ is_state('binary_sensor.ic_back_status', 'on') and is_state('binary_sensor.ic_front_status', 'on') }}"

  # https://github.com/kloggy/HA-Irrigation-Version2
  # If rain data has changed in the last 30 mins, then its raining.
  # - platform: template
  #   sensors:
  #     raining_now:
  #       friendly_name: "Raining Now"
  #       value_template: >-
  #         {{ state_attr('sensor.local_rain_30_min_statistics_raw', 'change')|float > 0 }}

  # Triggered template sensor that records each day’s maximum, to show yesterdays total rain.
  - trigger:
      - platform: time
        at: "23:59:50"
    sensor:
      - name: "Yesterdays Local Total Rain"
        unique_id: yesterdays_local_total_rain
        state: "{{ states('sensor.daily_rain_meter') }}"

####################################################
# rflink 433mhz Weather Station sensors
####################################################
sensor:
  - platform: rflink
    automatic_add: false
    devices:
      alectov5_00a3_temp:
        sensor_type: uv_intensity
        name: "Local UV Intensity"

      alectov5_00a3_rain:
        sensor_type: light_intensity
        name: "Local Light Intensity"

      alectov5_00a3_bat:
        sensor_type: battery
        name: "Weather Station Battery A"

      dkw2012_007d_temp:
        sensor_type: temperature
        name: "Local Outside Temperature"

      dkw2012_007d_hum:
        sensor_type: humidity
        name: "Local Outside Humidity"

      dkw2012_007d_winsp:
        sensor_type: windspeed
        name: "Local Wind Speed"

      dkw2012_007d_wings:
        sensor_type: windgusts
        name: "Local Wind Speed Gusts"

      dkw2012_007d_rain:
        sensor_type: total_rain
        name: "Local Total Rain"

      dkw2012_007d_windir:
        sensor_type: winddirection
        name: "Local Wind Direction"

      dkw2012_007d_bat:
        sensor_type: battery
        name: "Weather Station Battery B"

  # https://github.com/kloggy/HA-Irrigation-Version2
  # https://github.com/kloggy/HA-Irrigation-Version2/issues/44
  - platform: template
    sensors:
      irrigation_weather_outlook:
        friendly_name: "Irrigation weather outlook"
        icon_template: mdi:flower-outline
        value_template:
          | # "keep": keep the line feed, keep trailing blank lines. https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines
          Weather Outlook: 
          High: {{ state_attr('weather.openweathermap', 'forecast')[0].temperature }}°C
          Low: {{ state_attr('weather.openweathermap', 'forecast')[0].templow }}°C
          <br>
          Rain today: {{ state_attr('weather.openweathermap', 'forecast')[0].precipitation }} mm
          tomorrow: {{ state_attr('weather.openweathermap', 'forecast')[1].precipitation }} mm

  - platform: statistics
    name: Local Rain 24 Hours Statistics Raw
    entity_id: sensor.local_total_rain
    state_characteristic: change
    sampling_size: 4320 # Enough for 3 readings a minute
    max_age:
      hours: 24
  - platform: statistics # Raw values for 24 hours
    name: Local Rain 48 Hours Statistics Raw
    entity_id: sensor.local_total_rain
    state_characteristic: change
    sampling_size: 8320 # Enough for 3 readings a minute
    max_age:
      hours: 48

  # Rain values are cumulative, need to extract the "rate of change" to see the actual value.
  - platform: template
    sensors:
      template_rain_last_24_hours:
        friendly_name: "Local Rain 24 Hours"
        unit_of_measurement: "mm"
        value_template: "{{ state_attr('sensor.local_rain_24_hours_statistics_raw', 'change') }}"

  # # NEW - Working
  # - platform: template
  #   sensors:
  #     rain_day_0:
  #       friendly_name: "Rain Last 24 Hours"
  #       unit_of_measurement: "mm"
  #       value_template: "{{ state_attr('sensor.openweathermap_history', 'day_0_rain') }}"
  # # NEW - Working
  # - platform: template
  #   sensors:
  #     rain_day_1:
  #       friendly_name: "Rain Last 24-48 hours"
  #       unit_of_measurement: "mm"
  #       value_template: "{{ state_attr('sensor.openweathermap_history', 'day_1_rain') }}"

  # Difference between the 48 hours and 24 hours, to give the previous 24 hours.
  - platform: template
    sensors:
      template_rain_last_24_to_48_hours:
        friendly_name: "Local Rain Previous 24 Hours"
        unit_of_measurement: "mm"
        value_template: "{{ state_attr('sensor.local_rain_48_hours_statistics_raw', 'change') - state_attr('sensor.local_rain_24_hours_statistics_raw', 'change') }}"

  # This sensor is converted into a binary sensor via a template, to create a true/false state from the last xx mins of rain (rate of change sensor).
  - platform: statistics
    name: Local Rain 30 Min Statistics Raw
    entity_id: sensor.local_total_rain
    state_characteristic: change
    sampling_size: 180
    max_age:
      minutes: 30

# https://www.home-assistant.io/integrations/utility_meter/
utility_meter:
  rain_meter:
    source: sensor.local_total_rain
    name: Local Rainfall
    unique_id: local_rain_meter
  daily_rain_meter:
    source: sensor.local_total_rain
    name: Daily Local Rain
    unique_id: daily_rain_meter
    cycle: daily
  weekly_rain_meter:
    source: sensor.local_total_rain
    name: Weekly Local Rain
    unique_id: weekly_rain_meter
    cycle: weekly

# https://www.home-assistant.io/integrations/alert/
alert:
  irrigation_controller_alert:
    name: Irrigation Contollers Alert
    done_message: Irrigation contollers are back online
    message: >
      {% if not is_state('binary_sensor.ic_back_status', 'on') -%}
        Back garden irrigation contoller went offline
      {%- elif not is_state('binary_sensor.ic_front_status', 'on') -%}
        Front garden irrigation contoller went offline
      {%- endif %}
    entity_id: binary_sensor.irrigation_controllers_online
    state: "off"
    repeat:
      - 60
      - 120
      - 240
    can_acknowledge: true
    skip_first: true
    data:
      channel: Irrigation
      importance: default
      visibility: public
      notification_icon: mdi:water-alert-outline
    notifiers:
      - mobile_app_rich_mob_app
