############################################################
#
# Christmas Lights - Enabled Seasonally
#
# For mqtt contoller:
# see https://github.com/Genestealer/ESP8266-433Mhz-Controller-Gateway
#
# For rflink contoller:
# see https://github.com/Genestealer/Home-Assistant-RFLink-Gateway-ESP8266
############################################################

### Old
# - platform: mqtt
#   command_topic: "HUISHS/LightingGateway/transmit"
#   payload_on: "2006508"
#   payload_off: "2006500"
#   name: "Christmas Tree Bling"

# - platform: mqtt
#   command_topic: "HUISHS/LightingGateway/transmit"
#   payload_on: "2006509"
#   payload_off: "2006501"
#   name: "Star Light"

# - platform: mqtt
#   command_topic: "HUISHS/LightingGateway/transmit"
#   payload_on: "2006510"
#   payload_off: "2006502"
#   name: "Outside Lights"

# - platform: mqtt
#   command_topic: "HUISHS/LightingGateway/transmit"
#   payload_on: "2006511"
#   payload_off: "2006503"
#   name: "Snowflake Lights"

# 433MHz switchs
- platform: rflink
  device_defaults:
    signal_repetitions: 5
    fire_event: true
  devices:
    RFCustom_524643_6: # Status RCS-K09
      name: Christmas Sitting Room Star
    RFCustom_524643_8: # Status RCS-K09
      name: Christmas Bed Room Star
