############################################################
#
# MQTT Light Gatway
#
############################################################

- platform: mqtt
  command_topic: "HUISHS/LightingGateway/transmit"
  payload_on: "2006479"
  payload_off: "2006471"
  name: "MQTT Light 1"
  optimistic: true

- platform: mqtt
  command_topic: "HUISHS/LightingGateway/transmit"
  payload_on: "2006509"
  payload_off: "2006501"
  name: "MQTT Light 2"
  optimistic: true