############################################################
#
# RFLink Lights
#
############################################################

#433MHz
- platform: rflink
  device_defaults:
    signal_repetitions: 3
  devices:
    Maclean_0d82_01: # Lucy Room Lamp
      name: Lamp_1
    Maclean_0d82_02:
      name: Lamp_2
    Maclean_0d82_03:
      name: Lamp_3
    Maclean_0d82_04:
      name: Lamp_4
    Eurodomest_0fca6c_00:
      name: Upstairs Hall Light

#2.4MHz
- platform: rflink
  device_defaults:
    signal_repetitions: 5
  devices:
    ansluta_ce30_0: 
      name: Kitchen Under Counter Lights
      aliasses: Ansluta_ce30_0
  