############################################################
#
# RFLink Lights
#
############################################################

#433MHz
- platform: rflink
  device_defaults:
    signal_repetitions: 3
  devices:
    Maclean_0d82_01: # Lucy Room Lamp
      name: Lamp_1
    Maclean_0d82_02:
      name: Lamp_2
    Maclean_0d82_03:
      name: Lamp_3
    Maclean_0d82_04:
      name: Lamp_4



- platform: rflink
  device_defaults:
    signal_repetitions: 10
  devices:
    Eurodomest_0fca6c_00: # Note: Send TX command over and over agin, as it only seems to listen for them  occasionally. More tried helps ensure one makes it.
      name: Upstairs Hall Light #Energenie Wall Light Switch MIHO026, 

#2.4MHz
- platform: rflink
  device_defaults:
    signal_repetitions: 10
  devices:
    ansluta_ce30_0: 
      name: Kitchen Under Counter Lights
      aliasses: Ansluta_ce30_0
  