############################################################
#
# RFLink Lights, renamed in customise.yaml
#
############################################################

#433MHz
- platform: rflink
  device_defaults:
    signal_repetitions: 3
  devices:
    Maclean_0d82_01: # Lucy Room Lamp
      name: Lamp_1
    Maclean_0d82_02:
      name: Lamp_2
    Maclean_0d82_03:
      name: Lamp_3
    # Maclean_0d82_04:
    #   name: Lamp_4



- platform: rflink
  device_defaults:
    signal_repetitions: 10
  devices:
    Eurodomest_0fca6c_00: # Note: Send TX command over and over agin, as it only seems to listen for them  occasionally. More tried helps ensure one makes it.
      name: Lamp_4 # renamed in customise.yaml to 'Upstairs Hall Light' #Energenie Wall Light Switch MIHO026,


#Eurodomest_0fca6c_00:
# Off: Decimal: 219454 (24Bit) Binary: 000000110101100100111110 Tri-State: not applicable PulseLength: 309 microseconds Protocol: 1
# OFF Raw data: 9588,280,924,280,928,276,928,276,924,284,924,280,928,868,336,868,348,264,932,868,344,264,940,864,340,860,348,264,936,268,944,852,348,260,944,260,944,860,344,856,352,852,352,852,352,852,360,252,952,

# on Decimal: 219455 (24Bit) Binary: 000000110101100100111111 Tri-State: not applicable PulseLength: 309 microseconds Protocol: 1
# ON Raw data: 9588,280,928,272,928,276,932,272,932,268,928,284,920,872,344,864,344,268,940,860,340,264,940,864,340,860,348,264,940,264,944,856,352,256,948,256,952,860,344,860,348,852,352,852,364,840,360,848,360,


#2.4MHz
- platform: rflink
  device_defaults:
    signal_repetitions: 3
  devices:
    ansluta_ce30_0:
      name: Kitchen Under Counter Lights
      aliases: Ansluta_ce30_0
