############################################################
#
# Monitoring Dell R720 iDRAC 7
# 
# I am using iDRAC enterprise version "DRAC7/8 with Lifecycle Controller Version 2.65.65.65"
# iDRAC with Lifecycle Controller v. 2.65.65.65
# https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=0ghf4&oscode=naa&productcode=poweredge-r720
#
# 
# Baseoid's discovered through the use of trial and error
# and free scanning tool Paessler SNMP Tester. 
# https://www.paessler.com/tools/snmptester
#
############################################################



sensor:
############################################################
# SNMP Sensors
#
# SNMP sensors are missing features so I create the Raw
# sensors here and then create templated sensors with the
# desired customisation above.
#
# Baseoid's discovered through the use of trial and error
# and free scanning tool Paessler SNMP Tester. 
# https://www.paessler.com/tools/snmptester
#
############################################################
  # Raw Dell Server Power
  - platform: snmp
    host: !secret ServerIdracIP
    port: 161
    community: public
    name: RawDellServerPower
    baseoid: 1.3.6.1.4.1.674.10892.5.4.600.30.1.6.1.3
    unit_of_measurement: W


  - platform: snmp
    host: !secret ServerIdracIP
    port: 161
    community: public
    name: RawDellServerPSU1Current
    baseoid: 1.3.6.1.4.1.674.10892.5.4.600.30.1.6.1.1
    unit_of_measurement: A
    value_template: "{{((value | float) / 10) | float}}"

  - platform: snmp
    host: !secret ServerIdracIP
    port: 161
    community: public
    name: RawDellServerPSU2Current
    baseoid: 1.3.6.1.4.1.674.10892.5.4.600.30.1.6.1.2
    unit_of_measurement: A
    value_template: "{{((value | float) / 10) | float}}"

  - platform: snmp
    host: !secret ServerIdracIP
    port: 161
    community: public
    name: RawDellServerPSU1Voltage
    baseoid: 1.3.6.1.4.1.674.10892.5.4.600.20.1.6.1.26
    unit_of_measurement: V
    value_template: "{{((value | float) / 1000) | float}}"

  - platform: snmp
    host: !secret ServerIdracIP
    port: 161
    community: public
    name: RawDellServerPSU2Voltage
    baseoid: 1.3.6.1.4.1.674.10892.5.4.600.20.1.6.1.27
    unit_of_measurement: V
    value_template: "{{((value | float) / 1000) | float}}"
    
  # Raw Dell Server Thermals
  - platform: snmp
    host: !secret ServerIdracIP
    port: 161
    community: public
    name: RawDellServerInletTemperature
    baseoid: 1.3.6.1.4.1.674.10892.5.4.700.20.1.6.1.1
    unit_of_measurement: °C
    value_template: "{{((value | float) / 10) | float}}"

  - platform: snmp
    host: !secret ServerIdracIP
    port: 161
    community: public
    name: RawDellServerExhaustTemperature
    baseoid: 1.3.6.1.4.1.674.10892.5.4.700.20.1.6.1.2
    unit_of_measurement: °C
    value_template: "{{((value | float) / 10) | float}}"

  - platform: snmp
    host: !secret ServerIdracIP
    port: 161
    community: public
    name: RawDellServerCPU1Temperature
    baseoid: 1.3.6.1.4.1.674.10892.5.4.700.20.1.6.1.3
    unit_of_measurement: °C
    value_template: "{{((value | float) / 10) | float}}"

  - platform: snmp
    host: !secret ServerIdracIP
    port: 161
    community: public
    name: RawDellServerCPU2Temperature
    baseoid: 1.3.6.1.4.1.674.10892.5.4.700.20.1.6.1.4
    unit_of_measurement: °C
    value_template: "{{((value | float) / 10) | float}}"


  # Raw Dell Server Fans
  - platform: snmp
    host: !secret ServerIdracIP
    port: 161
    community: public
    name: RawDellServerFan1
    baseoid: 1.3.6.1.4.1.674.10892.5.4.700.12.1.6.1.1
    unit_of_measurement: RPM
  - platform: snmp
    host: !secret ServerIdracIP
    port: 161
    community: public
    name: RawDellServerFan2
    baseoid: 1.3.6.1.4.1.674.10892.5.4.700.12.1.6.1.2
    unit_of_measurement: RPM
  - platform: snmp
    host: !secret ServerIdracIP
    port: 161
    community: public
    name: RawDellServerFan3
    baseoid: 1.3.6.1.4.1.674.10892.5.4.700.12.1.6.1.3
    unit_of_measurement: RPM
  - platform: snmp
    host: !secret ServerIdracIP
    port: 161
    community: public
    name: RawDellServerFan4
    baseoid: 1.3.6.1.4.1.674.10892.5.4.700.12.1.6.1.4
    unit_of_measurement: RPM
  - platform: snmp
    host: !secret ServerIdracIP
    port: 161
    community: public
    name: RawDellServerFan5
    baseoid: 1.3.6.1.4.1.674.10892.5.4.700.12.1.6.1.5
    unit_of_measurement: RPM
  - platform: snmp
    host: !secret ServerIdracIP
    port: 161
    community: public
    name: RawDellServerFan6
    baseoid: 1.3.6.1.4.1.674.10892.5.4.700.12.1.6.1.6
    unit_of_measurement: RPM



# Sensor integration of energy monitoring.
# Accumulates the server energy used, from the templated sensor (Which in-turn gathers data from the SNMP sensor.)
# This sensor can be added to the home assistant energy dashboard as a statistic sensor for monitoring power consumption over time.
  - platform: integration
    source: sensor.server_power
    name: "Dell Server Energy"
    unit_prefix: k
    unit_time: h
    round: 2



# Templated sensor with all of the customisation features.
# These are the sensors that I show on my interface I don't typically show the raw sensors.
template: # https://www.home-assistant.io/integrations/template/#state-based-template-sensors
  - sensor:
      - name: "Server Power"
        state: "{{states('sensor.RawDellServerPower')}}"
        unit_of_measurement: W
        device_class: power #Power, watts. Not "Energy" i.e. Wh.
        state_class: measurement

      - name: "Server Inlet Temperature"
        state: "{{states('sensor.RawDellServerInletTemperature')}}"
        unit_of_measurement: °C
        device_class: temperature
        state_class: measurement

      - name: "Server Exhaust Temperature"
        state: "{{states('sensor.RawDellServerExhaustTemperature')}}"
        unit_of_measurement: °C
        device_class: temperature
        state_class: measurement

      - name: "Server CPU1 Temperature"
        state: "{{states('sensor.RawDellServerCPU1Temperature')}}"
        unit_of_measurement: °C
        device_class: temperature
        state_class: measurement

      - name: "Server CPU2 Temperature"
        state: "{{states('sensor.RawDellServerCPU2Temperature')}}"
        unit_of_measurement: °C
        device_class: temperature
        state_class: measurement

      - name: "Server Fans Speed Avg"
        state: >
           {{ (( states('sensor.rawdellserverfan1') | float +
                  states('sensor.rawdellserverfan2') | float +
                  states('sensor.rawdellserverfan3') | float +
                  states('sensor.rawdellserverfan4') | float +
                  states('sensor.rawdellserverfan5') | float +
                  states('sensor.rawdellserverfan6') | float) / 6) | round(0) }}
        unit_of_measurement: RPM
        icon: mdi:fan

