############################################################
#
# MQTT Irrigation Switch 1
#
############################################################

- platform: mqtt
  name: "Lawn Irrigation"
  state_topic: "HUISHS/Irrigation/OutputOne/State"
  command_topic: "HUISHS/Irrigation/OutputOne/Command"
  payload_on: "1"
  payload_off: "0"
  optimistic: false
  # qos: 0
  retain: true

############################################################
#
# MQTT Irrigation Switch 2
#
############################################################
- platform: mqtt
  name: "Pot Irrigation"
  state_topic: "HUISHS/Irrigation/OutputTwo/State"
  command_topic: "HUISHS/Irrigation/OutputTwo/Command"
  payload_on: "1"
  payload_off: "0"
  optimistic: false
  # qos: 0
  retain: true
