############################################################
#
# MQTT Irrigation Switch 1
#
############################################################

- platform: mqtt
  name: "Lawn Irrigation Valve"
  state_topic: "HUISHS/Irrigation/StatusJSON"
  value_template: '{{ value_json.Valve1 }}'
  payload_on: "1"
  payload_off: "0"
  command_topic: "HUISHS/Irrigation/OutputOne/Command"
  availability_topic: "HUISHS/Irrigation/Status"
  payload_available: "online"
  payload_not_available: "offline"
  optimistic: false
  retain: false

############################################################
#
# MQTT Irrigation Switch 2
#
############################################################
- platform: mqtt
  name: "Pot Irrigation Valve"
  state_topic: "HUISHS/Irrigation/StatusJSON"
  value_template: '{{ value_json.Valve2 }}'
  command_topic: "HUISHS/Irrigation/OutputTwo/Command"
  payload_on: "1"
  payload_off: "0"
  availability_topic: "HUISHS/Irrigation/Status"
  payload_available: "online"
  payload_not_available: "offline"
  optimistic: false
  retain: false
