############################################################
#
# MQTT 433mhz Switchs
#
# For contoller:
# see https://github.com/Genestealer/ESP8266-433Mhz-Controller-Gateway
#
############################################################

# 433MHz switchs
# THE BLIND GENIE Office Blinds
- platform: mqtt
  # entity_namespace: holiday_house
  command_topic: "HUISHS/LightingGateway/transmit"
  payload_on: "8442884"
  payload_off: "8442888"
  name: "Office Blinds"
  optimistic: true
  availability_topic: "HUISHS/LightingGateway/Status"
  payload_available: "online"
  payload_not_available: "offline"
