############################################################
#
# MQTT Switchs
#
############################################################

- platform: mqtt
  name: "Irrigation Switch"
  state_topic: "HUISHS/Irrigation/OutputOne/State"
  command_topic: "HUISHS/Irrigation/OutputOne/Command"
  payload_on: "1"
  payload_off: "0"
  optimistic: false
  # qos: 0
  retain: true
