############################################################
#
# RFLink Switchs
#
# For contoller:
# see https://github.com/Genestealer/Home-Assistant-RFLink-Gateway-ESP8266
#
# Remote types:
# - Maclean: MCE07GB Remote Control Sockets
# - Eurodomest: Energenie Wall Light Switch MIHO026
# - Ansluta: Ikea 2.4GHz Remote control (903.007.73)
# - RFCustom: Status RCS-K09 433MHz remote control socket
#
############################################################

# 433MHz switchs
- platform: rflink
  device_defaults:
    signal_repetitions: 3
    fire_event: true
  devices:
    EMW100_a140_0: # Ikea ANSLUTA E1202
      name: Kitchen Extractor Fan
      aliases: emw100_a140_00
    RFCustom_524643_0: # Status RCS-K09
      name: Bunny Fluff Air Filter
    RFCustom_524643_2: # Status RCS-K09
      name: Wax Melter
    # RFCustom_524643_4: # Status RCS-K09
    #   name: Plug-In Air Freshener
    Maclean_0d85_01: #
      name: Plug-In Air Freshener 1
    # ev1527_05d797_0e:
    #   name: Front Door Sensor
    tristate_0aaaa0_0:
      name: Smoke Machine
    Eurodomest_0d25be_00: # Energenie MIHO002 plug in stockets
       name: Plug-In Air Freshener 2
       signal_repetitions: 8 # It takes a few tried

    # chuango_103d16_02:
    #   name: 433 next door doorbell
    # chuango_351536_02:
    #   name: 433 may also next door doorbell 1
    # chuango_6a2a6c_02:
    #   name: 433 may also next door doorbell 2
    # conrad_95d593_06:
    #   name: 433 may also next door doorbell 3
    # elrodb_224c562b_1:
    #   name: 433 Someones doorbell
    #   # 20;4F;ElroDB;ID=224c562b;SWITCH=1;CMD=ON;CHIME=01;
    #    # 20;55;FA500;ID=0000895f;SWITCH=04;CMD=OFF;




    
# # Feb 2018: Removed and moved to "mqtt_switch.yaml" using my 433mhz MQTT controller
# # https://github.com/Genestealer/ESP8266-433Mhz-Controller-Gateway
# # This is because of limitations with the HASS rflink not allowing custom "on" and "off"
# # commands and being unable to program custom commands into the RFLink gatway firmware slots.
# # I.E. RFFIND command will not find the EV1527_xxxx
# #
# # 433MHz Office blinds
# - platform: rflink
#   device_defaults:
#     signal_repetitions: 1
#     fire_event: false
#   devices:
#     EV1527_080d40_8: # Office Blinds (THE BLIND GENIE)
#       name: Office Blinds Close
#     EV1527_080d40_4: # Office Blinds (THE BLIND GENIE)
#       name: Office Blinds Open


# # Ikea two button round remote
# - platform: rflink
#   device_defaults:
#     fire_event: true
#   devices:
#     emw100_d018_00:
#       name: Button 1
