############################################################
#
# RFLink Switchs
#
############################################################

- platform: rflink
  device_defaults:
    signal_repetitions: 3
    fire_event: true
  devices:
    EMW100_a140_0:
      name: Kitchen Extractor Fan
      aliasses: emw100_a140_00


- platform: rflink
  device_defaults:
    fire_event: true
  devices:
    emw100_d018_00:
      name: Button 1

- platform: rflink
  device_defaults:
    signal_repetitions: 3
  devices:
    RFCustom_524643_0:
      name: Bunny fluff air filter
