############################################################
#
# RFLink Switchs
#
############################################################

- platform: rflink
  device_defaults:
    signal_repetitions: 3
  devices:
    EMW100_a140_0:
      name: Kitchen Extractor Fan


- platform: rflink
  device_defaults:
    fire_event: true
  devices:
    emw100_d018_00:
      name: Button 1