############################################################
#
# Glances Sensor
#
############################################################
- platform: glances
  name: Server
  host: !secret glances_server_host
  port: !secret glances_server_port
  resources:
    - 'disk_use_percent'
    - 'disk_use'
    - 'disk_free'
    - 'memory_use_percent'
    - 'memory_use'
    - 'memory_free'
    - 'swap_use_percent'
    - 'swap_use'
    - 'swap_free'
    - 'processor_load'
    - 'process_running'
    - 'process_total'
    - 'process_thread'
    - 'process_sleeping'

# Note, other hard drive sensors are in the rest.yaml file
