############################################################
#
# Google Geocode
# Google geocode is the process of converting device tracker location into a human-readable address.
# https://github.com/michaelmcarthur/GoogleGeocode-HASS
############################################################
- platform: google_geocode
  name: Richard Street Location
  origin: person.richard
  # options: street_number, street, city
  options: street, city
  display_zone: hide
  # gravatar: youremail@address.com
  api_key: !secret googlemaps_api_key

- platform: google_geocode
  name: Lucy Street Location
  origin: person.lucy
  # options: street_number, street, city
  options: street, city
  display_zone: hide
  # gravatar: youremail@address.com
  api_key: !secret googlemaps_api_key
