############################################################
#
# HP Server Integrated Lights Out Monitoring
#
############################################################

- platform: hp_ilo
  name: Server
  host: !secret hp_ilo_server
  port: 443
  username: !secret hp_ilo_username
  password: !secret hp_ilo_password
  monitored_variables:
    # - server_name
  #  - server_fqdn
  #  - server_host_data
  ##  - server_power_status
    #- server_asset_tag
    # - server_uid_status
  ##  - server_health
    # - network_settings


############################################################
#
#  Server Templates
#
############################################################

- platform: template
  sensors:
    server_ilo_fan:
      value_template: '{{states.sensor.server_server_health.attributes.fans["Fan 1"]["speed"][0] }}'
      unit_of_measurement: '%'
      entity_id: sensor.server_server_health
      friendly_name: "Fan Speed"

    server_ilo_power:
      value_template: '{{states.sensor.server_server_health.attributes.health_at_a_glance["power_supplies"]["status"] }}'
      entity_id: sensor.server_server_health
      friendly_name: "Power Supplies"

    server_ilo_processor:
      value_template: '{{states.sensor.server_server_health.attributes.health_at_a_glance["processor"]["status"] }}'
      entity_id: sensor.server_server_health
      friendly_name: "Processor"

    server_ilo_storage:
      value_template: '{{states.sensor.server_server_health.attributes.health_at_a_glance["storage"]["status"] }}'
      entity_id: sensor.server_server_health
      friendly_name: "Storage"

    server_ilo_memory:
      value_template: '{{states.sensor.server_server_health.attributes.health_at_a_glance["memory"]["status"] }}'
      entity_id: sensor.server_server_health
      friendly_name: "Memory"

    server_ilo_temperature:
      value_template: '{{states.sensor.server_server_health.attributes.health_at_a_glance["temperature"]["status"] }}'
      entity_id: sensor.server_server_health
      friendly_name: "Temperature"

    server_ilo_fans:
      value_template: '{{states.sensor.server_server_health.attributes.health_at_a_glance["fans"]["status"] }}'
      entity_id: sensor.server_server_health
      friendly_name: "Fans"

    server_ilo_bios:
      value_template: '{{states.sensor.server_server_health.attributes.health_at_a_glance["bios_hardware"]["status"] }}'
      entity_id: sensor.server_server_health
      friendly_name: "BIOS"

    server_ilo_network:
      value_template: '{{states.sensor.server_server_health.attributes.health_at_a_glance["network"]["status"] }}'
      entity_id: sensor.server_server_health
      friendly_name: "Network"

    server_ilo_temperature_ambient:
      value_template: '{{states.sensor.server_server_health.attributes.temperature["01-Inlet Ambient"]["currentreading"][0] }}'
      unit_of_measurement: '°C'
      entity_id: sensor.server_server_health
      friendly_name: "Ambient"

    server_ilo_temperature_processor:
      value_template: '{{states.sensor.server_server_health.attributes.temperature["02-CPU"]["currentreading"][0] }}'
      unit_of_measurement: '°C'
      entity_id: sensor.server_server_health
      friendly_name: "Processor"

    server_ilo_temperature_memory:
      value_template: '{{states.sensor.server_server_health.attributes.temperature["03-P1 DIMM 1-2"]["currentreading"][0] }}'
      unit_of_measurement: '°C'
      entity_id: sensor.server_server_health
      friendly_name: "Memory"

    # server_temperature_HDD:
    #   value_template: '{{states.sensor.server_server_health.attributes.temperature["04-HD Max"]["currentreading"][0] }}'
    #   unit_of_measurement: '°C'
    #   entity_id: sensor.server_server_health
    #   friendly_name: "HDD"

    server_ilo_temperature_chipset:
      value_template: '{{states.sensor.server_server_health.attributes.temperature["05-Chipset"]["currentreading"][0] }}'
      unit_of_measurement: '°C'
      entity_id: sensor.server_server_health
      friendly_name: "Chipset"

    server_ilo_temperature_raid_controller:
      value_template: '{{states.sensor.server_server_health.attributes.temperature["10-PCI 1"]["currentreading"][0] }}'
      unit_of_measurement: '°C'
      entity_id: sensor.server_server_health
      friendly_name: "RAID Controller"

    # server_temperature_LOM:
    #   value_template: '{{states.sensor.server_server_health.attributes.temperature["13-LOM"]["currentreading"][0] }}'
    #   unit_of_measurement: '°C'
    #   entity_id: sensor.server_server_health
    #   friendly_name: "LOM"


    server_ilo_temperature_exhaust:
      value_template: '{{states.sensor.server_server_health.attributes.temperature["12-Sys Exhaust"]["currentreading"][0] }}'
      unit_of_measurement: '°C'
      entity_id: sensor.server_server_health
      friendly_name: "Exhaust"
