############################################################
#
# mqtt Sensors Bunny Shed
#
############################################################

- platform: mqtt
  state_topic: "HUISHS/BunnyShed/temperature"
  name: "Bunny Shed Temperature"
  unit_of_measurement: '°C'

# Icon done in # Done in homeassistant:customize
- platform: mqtt
  state_topic: "HUISHS/BunnyShed/humidity"
  name: "Bunny Shed Humidity"
  unit_of_measurement: '%'


- platform: mqtt
  state_topic: "HUISHS/BunnyShed/setTemperature"
  name: "Bunny Shed Target Temperature"
  unit_of_measurement: '°C'






#     # Template Binary Sensor https://home-assistant.io/components/binary_sensor.template/
#     # Because bunny_shed_heater_state is a 0 or 1 passed from MQTT and we want it to be binary
#   # - platform: template
#   #   sensors:
#   #     bunny_shed_heater:
#   #       # value_template: '{{ states.sensors.bunny_shed_heater_state | float > 0}}'
#   #       value_template: '{{states.sensors.bunny_shed_heater_state.state > 0}}'
#   #       friendly_name: 'Bunny Shed Heater On'


############################################################
#
# mqtt Kitchen
#
############################################################

- platform: mqtt
  state_topic: "HUISHS/Kitchen/temperature"
  name: "Kitchen Temperature"
  unit_of_measurement: '°C'

# Icon done in # Done in homeassistant:customize
- platform: mqtt
  state_topic: "HUISHS/Kitchen/humidity"
  name: "Kitchen Humidity"
  unit_of_measurement: '%'


############################################################
#
# Lighting Gateway Status
#
############################################################

- platform: mqtt
  state_topic: "HUISHS/LightingGateway/ClientName"
  name: "RF Gateway MQTT Client Name"
 
- platform: mqtt
  state_topic: "HUISHS/LightingGateway/IpAddress"
  name: "RF Gateway IP Address"

- platform: mqtt
  state_topic: "HUISHS/LightingGateway/SignalStrength"
  name: "RF Gateway Signal Strength"
  unit_of_measurement: "dBm"

- platform: mqtt
  state_topic: "HUISHS/LightingGateway/HostName"
  name: "RF Gateway IP Host Name"

- platform: mqtt
  state_topic: "HUISHS/LightingGateway/SSID"
  name: "RF Gateway SSID"

############################################################
#
# Bunny Shed Controller Status
#
############################################################

- platform: mqtt
  state_topic: "HUISHS/BunnyShed/ClientName"
  name: "Shed Controller Client Name"
 
- platform: mqtt
  state_topic: "HUISHS/BunnyShed/IpAddress"
  name: "Shed Controller IP Address"

- platform: mqtt
  state_topic: "HUISHS/BunnyShed/SignalStrength"
  name: "Shed Controller Signal Strength"
  unit_of_measurement: "dBm"

- platform: mqtt
  state_topic: "HUISHS/BunnyShed/HostName"
  name: "Shed Controller IP Host Name"

- platform: mqtt
  state_topic: "HUISHS/BunnyShed/SSID"
  name: "Shed Controller SSID"


