############################################################
#
# Irrigation Sensors: MQTT
#
############################################################

- platform: mqtt
  state_topic: "HUISHS/Irrigation/StatusJASON"
  name: "Soil Temperature"
  unit_of_measurement: '°C'
  value_template: '{{ value_json.SoilTemperature }}'
  availability_topic: "HUISHS/Irrigation/status"
  payload_available: "online"
  payload_not_available: "offline"

# Icon added in # Done in homeassistant:customize
- platform: mqtt
  state_topic: "HUISHS/Irrigation/StatusJASON"
  name: "Soil Capacitance"
  #unit_of_measurement: '%'
  value_template: '{{ value_json.SoilCapacitance }}'
  availability_topic: "HUISHS/Irrigation/status"
  payload_available: "online"
  payload_not_available: "offline"


############################################################
#
# Irrigation Sensors: Template
# https://community.home-assistant.io/t/hass-sprinkler/1903/30?u=richard.huish
#
############################################################

- platform: template
  sensors:
    pot_irrigation_duration:
      friendly_name: 'Set Duration'
      # entity_id: input_number.pot_irrigation_duration
      value_template: '00:{{states.input_number.pot_irrigation_duration.state | round(0)}}'

    pot_irrigation_last_run:
       friendly_name: 'Last Watered'
       # entity_id: switch.pot_irrigation_valve
       value_template: "{{states.switch.pot_irrigation_valve.last_changed.strftime('%a %D %-I:%M %P')}}"

    pot_irrigation_valve_status:
      friendly_name: 'Valve Status'
      value_template: "{% if states.switch.pot_irrigation_valve.state == 'on'%}Opened {{((as_timestamp(now()) - as_timestamp(states.switch.pot_irrigation_valve.last_changed)) / 60) | round(0) }} minutes ago{% else %}Closed{% endif %}"


    lawn_irrigation_duration:
      friendly_name: 'Set Duration'
      # entity_id: input_number.lawn_irrigation_duration
      value_template: '00:{{states.input_number.lawn_irrigation_duration.state | round(0)}}'

    lawn_irrigation_last_run:
       friendly_name: 'Last Watered'
       # entity_id: switch.lawn_irrigation_valve
       value_template: "{{states.switch.lawn_irrigation_valve.last_changed.strftime('%a %D %-I:%M %P')}}"

    lawn_irrigation_valve_status:
      friendly_name: 'Valve Status'
      value_template: "{% if states.switch.lawn_irrigation_valve.state == 'on'%}Opened {{((as_timestamp(now()) - as_timestamp(states.switch.lawn_irrigation_valve.last_changed)) / 60) | round(0) }} minutes ago{% else %}Closed{% endif %}"


   
