############################################################
#
# Irrigation Sensors: MQTT
#
############################################################

- platform: mqtt
  state_topic: "HUISHS/Irrigation/StatusJSON"
  name: "Soil Temperature"
  unit_of_measurement: '°C'
  value_template: '{{ value_json.SoilTemperature }}'
  availability_topic: "HUISHS/Irrigation/Status"
  payload_available: "online"
  payload_not_available: "offline"

# Icon added in # Done in homeassistant:customize
- platform: mqtt
  state_topic: "HUISHS/Irrigation/StatusJSON"
  name: "Soil Capacitance"
  #unit_of_measurement: '%'
  value_template: '{{ value_json.SoilCapacitance }}'
  availability_topic: "HUISHS/Irrigation/Status"
  payload_available: "online"
  payload_not_available: "offline"
