############################################################
#
# Bunny Shed Controller Status
#
############################################################

- platform: mqtt
  state_topic: "HUISHS/BunnyShed/statusJSON"
  name: "BS Client Name"
  value_template: '{{ value_json.ClientName }}'

- platform: mqtt
  state_topic: "HUISHS/BunnyShed/statusJSON"
  name: "BS IP"
  value_template: '{{ value_json.IP }}'

- platform: mqtt
  state_topic: "HUISHS/BunnyShed/statusJSON"
  name: "BS MAC"
  value_template: '{{ value_json.MAC }}'

- platform: mqtt
  state_topic: "HUISHS/BunnyShed/statusJSON"
  name: "BS RSSI"
  unit_of_measurement: "dBm"
  value_template: '{{ value_json.RSSI }}'

- platform: mqtt
  state_topic: "HUISHS/BunnyShed/statusJSON"
  name: "BS Host"
  value_template: '{{ value_json.HostName }}'

- platform: mqtt
  state_topic: "HUISHS/BunnyShed/statusJSON"
  name: "BS SSID"
  value_template: '{{ value_json.ConnectedSSID }}'

############################################################
#
# Lighting Gateway Status
#
############################################################

- platform: mqtt
  state_topic: "HUISHS/LightingGateway/statusJSON"
  name: "RFG Client Name"
  value_template: '{{ value_json.ClientName }}'

- platform: mqtt
  state_topic: "HUISHS/LightingGateway/statusJSON"
  name: "RFG IP"
  value_template: '{{ value_json.IP }}'

- platform: mqtt
  state_topic: "HUISHS/LightingGateway/statusJSON"
  name: "RFG MAC"
  value_template: '{{ value_json.MAC }}'

- platform: mqtt
  state_topic: "HUISHS/LightingGateway/statusJSON"
  name: "RFG RSSI"
  unit_of_measurement: "dBm"
  value_template: '{{ value_json.RSSI }}'

- platform: mqtt
  state_topic: "HUISHS/LightingGateway/statusJSON"
  name: "RFG Host"
  value_template: '{{ value_json.HostName }}'

- platform: mqtt
  state_topic: "HUISHS/LightingGateway/statusJSON"
  name: "RFG SSID"
  value_template: '{{ value_json.ConnectedSSID }}'

############################################################
#
# Irrigation Controller Status
#
############################################################

- platform: mqtt
  state_topic: "HUISHS/Irrigation/NodeHealthJSON"
  name: "IC Client Name"
  value_template: '{{ value_json.ClientName }}'

- platform: mqtt
  state_topic: "HUISHS/Irrigation/NodeHealthJSON"
  name: "IC IP"
  value_template: '{{ value_json.IP }}'

- platform: mqtt
  state_topic: "HUISHS/Irrigation/NodeHealthJSON"
  name: "IC MAC"
  value_template: '{{ value_json.MAC }}'

- platform: mqtt
  state_topic: "HUISHS/Irrigation/NodeHealthJSON"
  name: "IC RSSI"
  unit_of_measurement: "dBm"
  value_template: '{{ value_json.RSSI }}'

- platform: mqtt
  state_topic: "HUISHS/Irrigation/NodeHealthJSON"
  name: "IC Host"
  value_template: '{{ value_json.HostName }}'

- platform: mqtt
  state_topic: "HUISHS/Irrigation/NodeHealthJSON"
  name: "IC SSID"
  value_template: '{{ value_json.ConnectedSSID }}'

############################################################
#
# ESP-Link Controller Status
#
############################################################

- platform: mqtt
  state_topic: "HUISHS/esp-link"
  name: "ESP-Link Controller Signal Strength"
  unit_of_measurement: "dBm"
  expire_after: 125 # MQTT messages are only every 60 seconds, so 125 will permit it to miss two messages.
  value_template: '{{ value_json.rssi }}'