############################################################
#
# Bunny Shed Controller Status
#
############################################################

# # Example of using template to extract the json_attributes from the mqtt sensor.
# - platform: template
#   sensors:
#     bs_client_name:
#       friendly_name: "BS Client Name"
#       value_template: "{{ states.sensor.bs_client_name.attributes.ClientName }}"


- platform: mqtt
  state_topic: "HUISHS/BunnyShed/NodeHealthJSON"
  name: "BS Client Name"
  value_template: '{{ value_json.ClientName }}'
  availability_topic: "HUISHS/BunnyShed/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes:
    - ClientName
    - IP
    - MAC
    - RSSI
    - HostName
    - ConnectedSSID

- platform: mqtt
  state_topic: "HUISHS/BunnyShed/NodeHealthJSON"
  name: "BS IP"
  value_template: '{{ value_json.IP }}'
  availability_topic: "HUISHS/BunnyShed/status"
  payload_available: "online"
  payload_not_available: "offline"

- platform: mqtt
  state_topic: "HUISHS/BunnyShed/NodeHealthJSON"
  name: "BS MAC"
  value_template: '{{ value_json.MAC }}'
  availability_topic: "HUISHS/BunnyShed/status"
  payload_available: "online"
  payload_not_available: "offline"

- platform: mqtt
  state_topic: "HUISHS/BunnyShed/NodeHealthJSON"
  name: "BS RSSI"
  unit_of_measurement: "dBm"
  value_template: '{{ value_json.RSSI }}'
  availability_topic: "HUISHS/BunnyShed/status"
  payload_available: "online"
  payload_not_available: "offline"

- platform: mqtt
  state_topic: "HUISHS/BunnyShed/NodeHealthJSON"
  name: "BS Host"
  value_template: '{{ value_json.HostName }}'
  availability_topic: "HUISHS/BunnyShed/status"
  payload_available: "online"
  payload_not_available: "offline"

- platform: mqtt
  state_topic: "HUISHS/BunnyShed/NodeHealthJSON"
  name: "BS SSID"
  value_template: '{{ value_json.ConnectedSSID }}'
  availability_topic: "HUISHS/BunnyShed/status"
  payload_available: "online"
  payload_not_available: "offline"

############################################################
#
# Lighting Gateway Status
#
############################################################

- platform: mqtt
  state_topic: "HUISHS/LightingGateway/statusJSON"
  name: "RFG Client Name"
  value_template: '{{ value_json.ClientName }}'
  availability_topic: "HUISHS/LightingGateway/Status"
  payload_available: "online"
  payload_not_available: "offline"
  
- platform: mqtt
  state_topic: "HUISHS/LightingGateway/statusJSON"
  name: "RFG IP"
  value_template: '{{ value_json.IP }}'
  availability_topic: "HUISHS/LightingGateway/Status"
  payload_available: "online"
  payload_not_available: "offline"
  
- platform: mqtt
  state_topic: "HUISHS/LightingGateway/statusJSON"
  name: "RFG MAC"
  value_template: '{{ value_json.MAC }}'
  availability_topic: "HUISHS/LightingGateway/Status"
  payload_available: "online"
  payload_not_available: "offline"
  
- platform: mqtt
  state_topic: "HUISHS/LightingGateway/statusJSON"
  name: "RFG RSSI"
  unit_of_measurement: "dBm"
  value_template: '{{ value_json.RSSI }}'
  availability_topic: "HUISHS/LightingGateway/Status"
  payload_available: "online"
  payload_not_available: "offline"
  
- platform: mqtt
  state_topic: "HUISHS/LightingGateway/statusJSON"
  name: "RFG Host"
  value_template: '{{ value_json.HostName }}'
  availability_topic: "HUISHS/LightingGateway/Status"
  payload_available: "online"
  payload_not_available: "offline"
  
- platform: mqtt
  state_topic: "HUISHS/LightingGateway/statusJSON"
  name: "RFG SSID"
  value_template: '{{ value_json.ConnectedSSID }}'
  availability_topic: "HUISHS/LightingGateway/Status"
  payload_available: "online"
  payload_not_available: "offline"
  
############################################################
#
# Irrigation Controller Status
#
############################################################

- platform: mqtt
  state_topic: "HUISHS/Irrigation/NodeHealthJSON"
  name: "IC Client Name"
  value_template: '{{ value_json.ClientName }}'
  availability_topic: "HUISHS/Irrigation/status"
  payload_available: "online"
  payload_not_available: "offline"

- platform: mqtt
  state_topic: "HUISHS/Irrigation/NodeHealthJSON"
  name: "IC IP"
  value_template: '{{ value_json.IP }}'
  availability_topic: "HUISHS/Irrigation/status"
  payload_available: "online"
  payload_not_available: "offline"

- platform: mqtt
  state_topic: "HUISHS/Irrigation/NodeHealthJSON"
  name: "IC MAC"
  value_template: '{{ value_json.MAC }}'
  availability_topic: "HUISHS/Irrigation/status"
  payload_available: "online"
  payload_not_available: "offline"

- platform: mqtt
  state_topic: "HUISHS/Irrigation/NodeHealthJSON"
  name: "IC RSSI"
  unit_of_measurement: "dBm"
  value_template: '{{ value_json.RSSI }}'
  availability_topic: "HUISHS/Irrigation/status"
  payload_available: "online"
  payload_not_available: "offline"

- platform: mqtt
  state_topic: "HUISHS/Irrigation/NodeHealthJSON"
  name: "IC Host"
  value_template: '{{ value_json.HostName }}'
  availability_topic: "HUISHS/Irrigation/status"
  payload_available: "online"
  payload_not_available: "offline"

- platform: mqtt
  state_topic: "HUISHS/Irrigation/NodeHealthJSON"
  name: "IC SSID"
  value_template: '{{ value_json.ConnectedSSID }}'
  availability_topic: "HUISHS/Irrigation/status"
  payload_available: "online"
  payload_not_available: "offline"

############################################################
#
# ESP-Link Controller Status
#
############################################################

- platform: mqtt
  state_topic: "HUISHS/esp-link"
  name: "ESP-Link Controller Signal Strength"
  unit_of_measurement: "dBm"
  expire_after: 125 # MQTT messages are only every 60 seconds, so 125 will permit it to miss two messages.
  value_template: '{{ value_json.rssi }}'



  ############################################################
  #
  # TOR DoorBell Controller Status
  #
  ############################################################

- platform: mqtt
  state_topic: "HUISHS/DoorBell/StatusJSON"
  name: "TOR DB Client Name"
  value_template: '{{ value_json.ClientName }}'
  availability_topic: "HUISHS/DoorBell/Status"
  payload_available: "online"
  payload_not_available: "offline"

- platform: mqtt
  state_topic: "HUISHS/DoorBell/StatusJSON"
  name: "TOR DB IP"
  value_template: '{{ value_json.IP }}'
  availability_topic: "HUISHS/DoorBell/Status"
  payload_available: "online"
  payload_not_available: "offline"

- platform: mqtt
  state_topic: "HUISHS/DoorBell/StatusJSON"
  name: "TOR DB MAC"
  value_template: '{{ value_json.MAC }}'
  availability_topic: "HUISHS/DoorBell/Status"
  payload_available: "online"
  payload_not_available: "offline"

- platform: mqtt
  state_topic: "HUISHS/DoorBell/StatusJSON"
  name: "TOR DB RSSI"
  unit_of_measurement: "dBm"
  value_template: '{{ value_json.RSSI }}'
  availability_topic: "HUISHS/DoorBell/Status"
  payload_available: "online"
  payload_not_available: "offline"

- platform: mqtt
  state_topic: "HUISHS/DoorBell/StatusJSON"
  name: "TOR DB Host"
  value_template: '{{ value_json.HostName }}'
  availability_topic: "HUISHS/DoorBell/Status"
  payload_available: "online"
  payload_not_available: "offline"

- platform: mqtt
  state_topic: "HUISHS/DoorBell/StatusJSON"
  name: "TOR DB SSID"
  value_template: '{{ value_json.ConnectedSSID }}'
  availability_topic: "HUISHS/DoorBell/Status"
  payload_available: "online"
  payload_not_available: "offline"
