############################################################
#
# mqtt Sensors Bunny Shed
#
############################################################

- platform: mqtt
  state_topic: "HUISHS/BunnyShed/temperature"
  name: "Bunny Shed Temperature"
  unit_of_measurement: '째C'

# Icon done in # Done in homeassistant:customize
- platform: mqtt
  state_topic: "HUISHS/BunnyShed/humidity"
  name: "Bunny Shed Humidity"
  unit_of_measurement: '%'


- platform: mqtt
  state_topic: "HUISHS/BunnyShed/setHeaterTemperature"
  name: "Bunny Shed Target Heat Temperature"
  unit_of_measurement: '째C'

- platform: mqtt
  state_topic: "HUISHS/BunnyShed/setCoolerTemperature"
  name: "Bunny Shed Target Cool Temperature"
  unit_of_measurement: '째C'




#     # Template Binary Sensor https://home-assistant.io/components/binary_sensor.template/
#     # Because bunny_shed_heater_state is a 0 or 1 passed from MQTT and we want it to be binary
#   # - platform: template
#   #   sensors:
#   #     bunny_shed_heater:
#   #       # value_template: '{{ states.sensors.bunny_shed_heater_state | float > 0}}'
#   #       value_template: '{{states.sensors.bunny_shed_heater_state.state > 0}}'
#   #       friendly_name: 'Bunny Shed Heater On'


############################################################
#
# mqtt Kitchen
#
############################################################

- platform: mqtt
  state_topic: "HUISHS/LightingGateway/sensorJSON"
  name: "Kitchen Temperature"
  unit_of_measurement: '째C'
  value_template: '{{ value_json.Temperature }}'

# Icon done in # Done in homeassistant:customize
- platform: mqtt
  state_topic: "HUISHS/LightingGateway/sensorJSON"
  name: "Kitchen Humidity"
  unit_of_measurement: '%'
  value_template: '{{ value_json.Humidity }}'


############################################################
#
# Lighting Gateway Status
#
############################################################

- platform: mqtt
  state_topic: "HUISHS/LightingGateway/statusJSON"
  name: "RFG Client Name"
  value_template: '{{ value_json.ClientName }}'

- platform: mqtt
  state_topic: "HUISHS/LightingGateway/statusJSON"
  name: "RFG IP"
  value_template: '{{ value_json.IP }}'

- platform: mqtt
  state_topic: "HUISHS/LightingGateway/statusJSON"
  name: "RFG MAC"
  value_template: '{{ value_json.MAC }}'

- platform: mqtt
  state_topic: "HUISHS/LightingGateway/statusJSON"
  name: "RFG RSSI"
  unit_of_measurement: "dBm"
  value_template: '{{ value_json.RSSI }}'

- platform: mqtt
  state_topic: "HUISHS/LightingGateway/statusJSON"
  name: "RFG Host"
  value_template: '{{ value_json.HostName }}'

- platform: mqtt
  state_topic: "HUISHS/LightingGateway/statusJSON"
  name: "RFG SSID"
  value_template: '{{ value_json.ConnectedSSID }}'

############################################################
#
# Bunny Shed Controller Status
#
############################################################

- platform: mqtt
  state_topic: "HUISHS/BunnyShed/ClientName"
  name: "Shed Controller Client Name"

- platform: mqtt
  state_topic: "HUISHS/BunnyShed/IpAddress"
  name: "Shed Controller IP Address"

- platform: mqtt
  state_topic: "HUISHS/BunnyShed/SignalStrength"
  name: "Shed Controller Signal Strength"
  unit_of_measurement: "dBm"

- platform: mqtt
  state_topic: "HUISHS/BunnyShed/HostName"
  name: "Shed Controller IP Host Name"

- platform: mqtt
  state_topic: "HUISHS/BunnyShed/SSID"
  name: "Shed Controller SSID"



############################################################
#
# Irrigation Controller Status
#
############################################################

- platform: mqtt
  state_topic: "HUISHS/Irrigation/ClientName"
  name: "Irrigation Controller Client Name"

- platform: mqtt
  state_topic: "HUISHS/Irrigation/IpAddress"
  name: "Irrigation Controller IP Address"

- platform: mqtt
  state_topic: "HUISHS/Irrigation/SignalStrength"
  name: "Irrigation Controller Signal Strength"
  unit_of_measurement: "dBm"

- platform: mqtt
  state_topic: "HUISHS/Irrigation/HostName"
  name: "Irrigation Controller IP Host Name"

- platform: mqtt
  state_topic: "HUISHS/Irrigation/SSID"
  name: "Irrigation Controller SSID"


############################################################
#
# ESP-Link Controller Status
#
############################################################

- platform: mqtt
  state_topic: "HUISHS/esp-link"
  name: "ESP-Link Controller Signal Strength"
  unit_of_measurement: "dBm"
  expire_after: 125 # MQTT messages are only every 60 seconds, so 125 will permit it to miss two messages.
  value_template: '{{ value_json.rssi }}'
