############################################################
#
# Pi Hole Sensor
#
############################################################

- platform: pi_hole
  host: !secret piHoleIP
  monitored_conditions:
    - ads_blocked_today
    - dns_queries_today
    - ads_percentage_today
