############################################################
#
# RESTful Sensor for extra data from Glances which the
# normal Glances Sensor cannot do.
#
# Example !secret = http://192.168.1.20:61208/api/3/fs
# /api/3/fs returns a list of system volumes/disks
# Note, other sensors are in the glances.yaml file
############################################################

- platform: rest
  resource: !secret glances_HDD
  name: Disk 1 Drive Size #System Drive Size
  value_template: '{{ value_json[0].size | multiply(0.000000000001) | round(1) }}'
  unit_of_measurement: TB
- platform: rest
  resource: !secret glances_HDD
  name: Drive 1 Percent Used #System Drive Percent Used
  value_template: '{{ value_json[0].percent }}'
  unit_of_measurement: Percent

- platform: rest
  resource: !secret glances_HDD
  name: Disk 2 Drive Size
  value_template: '{{ value_json[1].size | multiply(0.000000000001) | round(1) }}'
  unit_of_measurement: TB
- platform: rest
  resource: !secret glances_HDD
  name: Drive 2 Percent Used
  value_template: '{{ value_json[1].percent }}'
  unit_of_measurement: Percent

- platform: rest
  resource: !secret glances_HDD
  name: Disk 3 Drive Size
  value_template: '{{ value_json[2].size | multiply(0.000000000001) | round(1) }}'
  unit_of_measurement: TB
- platform: rest
  resource: !secret glances_HDD
  name: Drive 3 Percent Used
  value_template: '{{ value_json[2].percent }}'
  unit_of_measurement: Percent

- platform: rest
  resource: !secret glances_HDD
  name: Disk 4 Drive Size
  value_template: '{{ value_json[3].size | multiply(0.000000000001) | round(1) }}'
  unit_of_measurement: TB
- platform: rest
  resource: !secret glances_HDD
  name: Drive 4 Percent Used
  value_template: '{{ value_json[3].percent }}'
  unit_of_measurement: Percent

- platform: rest
  resource: !secret glances_HDD
  name: Disk 5 Drive Size
  value_template: '{{ value_json[4].size | multiply(0.000000000001) | round(1) }}'
  unit_of_measurement: TB
- platform: rest
  resource: !secret glances_HDD
  name: Drive 5 Percent Used
  value_template: '{{ value_json[4].percent }}'
  unit_of_measurement: Percent

- platform: rest
  resource: !secret glances_HDD
  name: Disk 6 Drive Size
  value_template: '{{ value_json[5].size | multiply(0.000000000001) | round(1) }}'
  unit_of_measurement: TB
- platform: rest
  resource: !secret glances_HDD
  name: Drive 6 Percent Used
  value_template: '{{ value_json[5].percent }}'
  unit_of_measurement: Percent

# - platform: rest
#   resource: !secret glances_HDD
#   name: Backup Drive Size
#   value_template: '{{ value_json[2].size | multiply(0.000000000001) | round(1) }}'
#   unit_of_measurement: TB
#
# - platform: rest
#   resource: !secret glances_HDD
#   name: Backup Drive Percent Used
#   value_template: '{{ value_json[2].percent }}'
#   unit_of_measurement: Percent
#
#
# - platform: rest
#   resource: !secret glances_HDD
#   name: RAID5 Array Size
#   value_template: '{{ value_json[3].size | multiply(0.000000000001) | round(1) }}'
#   unit_of_measurement: TB
#
# - platform: rest
#   resource: !secret glances_HDD
#   name: RAID5 Array Percent Used
#   value_template: '{{ value_json[3].percent }}'
#   unit_of_measurement: Percent
#
#
# - platform: rest
#   resource: !secret glances_HDD
#   name: File History Drive Size
#   value_template: '{{ value_json[4].size | multiply(0.000000000001) | round(1) }}'
#   unit_of_measurement: TB
#
# - platform: rest
#   resource: !secret glances_HDD
#   name: File History Drive Percent Used
#   value_template: '{{ value_json[4].percent }}'
#   unit_of_measurement: Percent
#
# - platform: rest
#   resource: !secret glances_HDD
#   name: CCTV Drive Size
#   value_template: '{{ value_json[5].size | multiply(0.000000000001) | round(1) }}'
#   unit_of_measurement: TB
