############################################################
#
# RFLink  Sensor
#
############################################################

# 433MHz automated add
- platform: rflink
  automatic_add: true
  device_defaults:
    fire_event: true
    signal_repetitions: 10
############################################################
#
# RFLink House Mains Measurement
#
# Superseded by ESPHome Pulse Meter Sensor
#  on my doorbell_controller_electricity_monitor
#  So no longer need to find wattage from Current and Voltage.
#   E.G. {{states('sensor.house_power_meter') | float * (states('sensor.ups_input_voltage') | float / 1000)}}
#
############################################################

# # OWL CM113 sends Amps / Current in hexadecimal and not Watts, but you will have to convert it from hex to dec.
# # Home assistant will error each time the send value is not in dec.
# # Ref: https://github.com/home-assistant/core/issues/9564
# - platform: rflink
#   devices:
#     owl_cm113_ea23_current2:
#       sensor_type: current_phase_1
#       name: 'Unscaled House Consumption Current'
#       unit_of_measurement: A in HEX
# # Convert the hex to dec.
# # Ref: https://github.com/home-assistant/core/issues/9564
# - platform: template
#   sensors:
#     house_current_consumption:
#       # value_template: "{{states('sensor.unscaled_house_consumption_current') |int(base=16)  |int / 10 * 0.997 }}"
#       value_template: "{{states('sensor.unscaled_house_consumption_current') |int(base=16)  |int / 10 }}"
#       friendly_name: 'House Current Consumption'
#       unit_of_measurement: 'A'
#       availability_template: "{% if is_state('binary_sensor.esp_link_status', 'on') %} true {% endif %}"

# - platform: template
#   sensors:
#     true_house_current_consumption:
#       value_template: "{{states('sensor.unscaled_house_consumption_current') | int / 10}}"
#       friendly_name: 'House Current Consumption'
#       unit_of_measurement: 'A'
#       availability_template: "{% if is_state('binary_sensor.esp_link_status', 'on') %} true {% endif %}"

# # Using live measured voltage from UPS calculate total wattage
# - platform: template
#   sensors:
#     house_wattage:
#       value_template: "{{states('sensor.house_current_consumption') | int * (states('sensor.ups_input_voltage') | int / 1000)}}"
#       friendly_name: 'House Wattage'
#       unit_of_measurement: 'kW'
#       availability_template: "{% if is_state('binary_sensor.esp_link_status',  'on' and states('binary_sensor.usp_network_online')) %} true {% endif %}"
