############################################################
#
# Speed Test Sensor
#
############################################################

- platform: speedtest
  monitored_conditions:
   - ping
   - download
   - upload