############################################################
#
# SSL Cert Sensor
#
############################################################

- platform: command_line
  name: SSL cert expiry
  unit_of_measurement: days
  scan_interval: 10800
  command: "ssl-cert-check -b -c /etc/letsencrypt/live/server.richardhuish.com/cert.pem | awk '{ print $NF }'"