############################################################
#
# System Monitor
# For local system infomation
#
############################################################
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: memory_use_percent
    - type: load_1m
    - type: load_5m
    - type: processor_use
    - type: swap_use_percent
