############################################################
#
# Weather Sensor - darksky
#
############################################################

- platform: darksky
  api_key: !secret dark_sky_key
  units: uk2
  forecast:
    - 0 # Today only
    - 1 # Tommorrow
  hourly_forecast:
    - 0
    - 1
  monitored_conditions:
    - temperature_high
    - temperature_low
    - precip_intensity
    - wind_speed
    - temperature
    - humidity

    # https://github.com/kloggy/HA-Irrigation-Version2/blob/9cf6ce36d7c3f60e64a9302c6d9e16ab1a55174c/Weather%20Sensors.md
    - summary # The fifth sensor needs to return any text string describing the weather outlook (or anything else you want!).
    - icon
    # https://github.com/kloggy/HA-Irrigation-Version2/blob/9cf6ce36d7c3f60e64a9302c6d9e16ab1a55174c/prerequisites.yaml
    - minutely_summary
# ############################################################
# #
# # Weather Sensor - Weather Underground (wunderground)
# # https://home-assistant.io/components/sensor.wunderground/
# #
# #They no longer offer free API keys, it will be  disabled Dec 31, 2018
# ############################################################
# - platform: wunderground
#   api_key: !secret WUnderground_API
#   monitored_conditions:
#     - precip_today_metric #Total precipitation in metric units
#     - precip_1d_mm # Forecasted precipitation intensity in millimeters
#     - temp_low_1d_c # Forecasted low temperature in Celsius
#     - temp_high_1d_c # Forecasted high temperature in Celsius
#     - temp_c # Current temperature in Celsius
#     - relative_humidity # Relative humidity
#     - feelslike_c # Feels like (or apparent) temperature in Celsius
#     - precip_1d # Forecasted precipitation probability in %
#     - wind_mph # Current wind speed in mph
#     - wind_1d_mph # Forecasted wind speed in mph
#     - alerts
#     - weather
