############################################################
#
# Weather Sensor - darksky
#
############################################################

- platform: darksky
  api_key: !secret dark_sky_key
  units: uk2
  monitored_conditions:
    - temperature
    - humidity
    - summary
    - daily_summary
    - hourly_summary
    - temperature_max
    - temperature_min
    #- summary
    # - icon
    # - nearest_storm_distance
    # - nearest_storm_bearing
    # - precip_type
    # - precip_intensity
    # - precip_probability
    # - temperature
    # - apparent_temperature
    # - dew_point
    # - wind_speed
    # - wind_bearing
    # - cloud_cover
    # - humidity
    # - pressure
    # - visibility
    # - ozone
    # - minutely_summary
    #  - hourly_summary
    #  - daily_summary

    # - apparent_temperature_max
    # - apparent_temperature_min
    # - precip_intensity_max

############################################################
#
# Weather Sensor - Weather Underground (wunderground)
# https://home-assistant.io/components/sensor.wunderground/
#
############################################################
- platform: wunderground
  api_key: !secret WUnderground_API
  monitored_conditions:
    - precip_today_metric
    # - precip_1d_metric
