############################################################
#
# Home Assistant Camera Configuration
#
############################################################

- platform: mjpeg
  mjpeg_url: !secret CCTV1
  name: Front Door

- platform: mjpeg
  mjpeg_url: !secret CCTV2
  name: Other Camera