############################################################
#
# Home Assistant Camera Configuration
#
############################################################

- platform: mjpeg
  mjpeg_url: !secret axis_front_door_ip_mjpg
  name: Front Door
  username: !secret axis_front_door_username
  password: !secret axis_front_door_password

- platform: mjpeg
  mjpeg_url: !secret axis_front_drive_IP_mjpg
  name: Front of House
  username: !secret axis_front_drive_username
  password: !secret axis_front_drive_password

- platform: mjpeg
  mjpeg_url: !secret axis_garage_IP_mjpg
  name: Garage
  username: !secret axis_garage_username
  password: !secret axis_garage_password

- platform: mjpeg
  mjpeg_url: !secret Bunny_CCTV_mjpg
  name: Bunny Camera
  username: !secret Bunny_CCTV_username
  password: !secret Bunny_CCTV_password

# Needs FFMPEG, not currently installed.
# - platform: onvif
#   host: !secret Bunny_shed_onvif
#   name: Bunny Shed Camera