##############################################################
# Richard Huish 2025
# https://github.com/genestealer/Home-Assistant-Configuration
# https://www.home-assistant.io/integrations/bluetooth
# Office Air Purifier Control
# Sources: https://github.com/esphome/bluetooth-proxies
##############################################################
# Config Header for Device
##############################################################
substitutions:
  # Names
  name: bluetooth-proxy
  friendly_name: "Bluetooth Proxy"
  ui_comment: "Bluetooth Proxy" # Only shows in UI.
  
  # Wifi Settings
  ip: 192.168.2.53
  gateway: 192.168.2.1
  subnet: 255.255.255.0

  # Board Settings
  status_led: D0 
  status_led_inverted: "false"

  
  # Debug Component
  log_level: DEBUG  

  # Project 
  project_name: "Richard.TBD"
  project_version: "1.0.0"
  package_import_url: "TBD"

##############################################################
# Platform
##############################################################
esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

##############################################################
# Import shared code
##############################################################

# Packages 
packages:
  device_base: !include common/device_base.yaml
  wifi: !include common/device_base_wifi.yaml
# To remove status_led for a specific device, uncomment the line below:
status_led: !remove

# esphome:

# dashboard_import:
#   package_import_url: ${package_import_url}
#   import_full_config: false # or true

##############################################################
# Main Code
##############################################################


    
esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: true

bluetooth_proxy:
  active: true