esphome:
  name: bunny_shed_climate_control
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret IoT_VLAN_SSID
  password: !secret IoT_VLAN_SSID_Key

  manual_ip:
    static_ip: 192.168.2.40
    gateway: 192.168.2.1
    subnet: 255.255.255.0
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "jLkM#mJJMH7#xG@Y"

ota:
  password: "jLkM#mJJMH7#xG@Y"

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery_prefix: homeassistant
  discovery: true
#  topic_prefix: homeassistant




# sensor:
#   - platform: dht
#     pin: GPIO5
#     temperature:
#       name: "Bunny Shed Temperature"
#     humidity:
#       name: "Bunny Shed Humidity"
#     update_interval: 60s
#     model: DHT11


# remote_transmitter:
#   pin: GPIO2
#   carrier_duty_percent: 100%

# # Individual switches
# switch:
#   - platform: template
#     name: "Heater On"
#     turn_on_action:
#       - remote_transmitter.transmit_rc_switch_raw:
#           code: '000111101001111101011111'
#           protocol: 1

remote_receiver:
  pin: 
    number: GPIO14
    # inverted: false
    # mode: INPUT_PULLUP
  dump: rc_switch
  tolerance: 50%
  filter: 250us
  idle: 4ms
  buffer_size: 2kb
# https://github.com/esphome/issues/issues/19