#***************************************************
#   BusyLight Presence Indicator
#     Light Component
#   Richard Huish 2020
#   I built so my family can know when I'm busy and working in my Home Office.
#   ESP8266 based with local home-assistant.io GUI with controller with physical buttons and mini display
#   ----------
#   Github: https://github.com/genestealer/Home-Assistant-Configuration/tree/master/esphome
#   ----------
#   GUI: Locally hosted home assistant on network https://www.home-assistant.io/
#   API: Locally hosted native API component https://esphome.io/components/api.html
#   OTA updates: https://esphome.io/components/ota.html
#   ----------
#   The circuit:
#     Adafruit Feather HUZZAH with ESP8266 https://www.adafruit.com/product/2821
#     Breadboard-friendly RGB Smart NeoPixel https://www.adafruit.com/product/1312
#     4-channel I2C-safe Bi-directional Logic Level Converter - BSS138 https://www.adafruit.com/product/757
#     Ping pong ball to diffuse 
#   Inputs:
#     BusyLight Presence Indicator Controller via Home Assistant
#   Outputs:
#     NeoPixel, via Logic Level Converter as NeoPixel needs 5V and ESP8266 is 3.3V.
#****************************************************

esphome:
  name: busylight02
  platform: ESP8266
  board: huzzah

wifi:
  ssid: !secret IoT_VLAN_SSID
  password: !secret IoT_VLAN_SSID_Key
  manual_ip:
    static_ip: 192.168.2.34
    gateway: 192.168.2.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "hxN#^fPPv5ZRy%7l"

ota:
  password: "hxN#^fPPv5ZRy%7l"
  
sensor:
  - platform: wifi_signal
    name: "Busy Light 2 RSSI"
    update_interval: 60s
    
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Busy Light 2 IP"
    ssid:
      name: "Busy Light 2 SSID"
    bssid:
      name: "Busy Light 2 BSSID" 

status_led:
  pin: GPIO02

light:
  - platform: neopixelbus
    method: ESP8266_UART1
    type: GRB
    pin: GPIO2
    num_leds: 1
    name: "Busy Light 2"