#***************************************************
# Ice Maker Controller
####################################################
# Config Header for Device
####################################################
substitutions:
  devicename: icemaker
  upper_devicename: Ice Maker
  ip: 192.168.2.40
  pass: hxN#^fPPv5ZRy%7l
  
####################################################
# Shared code from all my projects
####################################################
esphome:
  name: $devicename
  platform: ESP8266
  board: nodemcuv2
wifi:
  ssid: !secret IoT_VLAN_SSID
  password: !secret IoT_VLAN_SSID_Key
  manual_ip:
    static_ip: $ip
    gateway: 192.168.2.1
    subnet: 255.255.255.0

logger: # Enable logging

api: # Enable Home Assistant API
  password: $pass

ota: # Enable over the air updates
  password: $pass

status_led:
  pin:
    number: D0 # GPIO16 - NodeMCU on-board LED
    inverted: True # To save power with using a coil relay

####################################################
# Non-Shared Code (May contain shared code)
####################################################  

font:
  - file: "fonts/comic.ttf"
    id: my_font
    size: 20
  - file: "fonts/comic.ttf"
    id: my_fontbismall
    size: 17
i2c:
  sda: GPIO4
  scl: GPIO5

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    # reset_pin: D0
    address: 0x3C
    # lambda: |-
    #   it.print(0, 0, id(my_font), "Free");
    #   it.print(0, 20, id(my_font), "Working");
    #   it.print(0, 40, id(my_font), "On Call");
    #   it.printf(it.get_width(), 0, id(my_fontbismall), TextAlign::TOP_RIGHT, "%s", id(confirmed_selected_state_text).state.c_str());
  #    it.printf(it.get_width(), 22, id(my_fontbismall), TextAlign::TOP_RIGHT, "%s", id(bssid).state.c_str());
  # it.image(0, 0, id(my_image));
  
binary_sensor:
  - platform: status
    name:  ${upper_devicename} Status

switch:
  - platform: gpio
    pin:
      number: D5
      mode: OUTPUT
    id: ICE_MAKER_SWITCH
    # restore_mode: RESTORE_DEFAULT_ON  
    name: "Ice Maker Switch"

# fan:
#   - platform: binary
#     output: ICE_MAKER_SWITCH
#     name: "Ice Maker"

  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button A"
  - platform: gpio
    pin:
      number: GPIO16
      mode: INPUT_PULLUP
      inverted: True
    name: "Button B"
  - platform: gpio
    pin:
      number: GPIO2
      mode: INPUT_PULLUP
      inverted: True
    name: "Button C"

dallas:
  - pin: D3    

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${upper_devicename} IP
    ssid:
      name: ${upper_devicename} SSID
    bssid:
      name: ${upper_devicename} BSSID

sensor:
  - platform: wifi_signal
    name: ${upper_devicename} RSSI
    update_interval: 300s
    
  - platform: dallas
    address: 0x93001414B455FF28
    name: "Ice Maker Water Temperature"
