esphome:
  name: indoor_bunny_house
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret IoT_VLAN_SSID
  password: !secret IoT_VLAN_SSID_Key
  manual_ip:
    static_ip: 192.168.2.37
    gateway: 192.168.2.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "of4zH*IxKw49yt@H"

ota:
  password: "of4zH*IxKw49yt@H"

status_led:
  pin: D0 #GPIO16


text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Indoor Bunny House Sensor IP"
    ssid:
      name: "Indoor Bunny House SSID"
    bssid:
      name: "Indoor Bunny House Connected BSSID"
      
sensor:
  - platform: wifi_signal
    name: "Indoor Bunny House RSSI"
    update_interval: 60s
    
  - platform: dht
    pin: D1 # GPIO5
    temperature:
      name: "Indoor Bunny House Temperature"
    humidity:
      name: "Indoor Bunny House Humidity"
    update_interval: 60s
    model: DHT22
