esphome:
  name: mini_display
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret IoT_VLAN_SSID
  password: !secret IoT_VLAN_SSID_Key
  manual_ip:
    static_ip: 192.168.2.32
    gateway: 192.168.2.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "hxN#^fPPv5ZRy%7l"

ota:
  password: "hxN#^fPPv5ZRy%7l"

i2c:


font:
  - file: "ComicSansMS3.ttf"
    id: my_font
    size: 20
    
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    reset_pin: D0
    address: 0x3C
    lambda: |-
      it.print(0, 0, id(my_font), "Hello World!");