homeassistant:
  enabled: true
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: hee5aeseth8ke9eeZaepheeloWiezeefax6xa2LapaQuaezoh4zi0vohthieGoor
serial:
  port: tcp://192.168.10.35:20108
  adapter: zstack
frontend:
  enabled: true
  port: 8099
advanced:
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
  channel: 25
  log_level: info
  last_seen: ISO_8601
device_options: {}
devices:
  '0x000b57fffe38a445':
    friendly_name: Test Remote
    legacy: false
    icon: device_icons/0bb605a453f07b8806fb5bd0288dd434.png
  '0x588e81fffe787201':
    friendly_name: Spare
  '0x60a423fffef26f3c':
    friendly_name: Kitchen Motion Sensor 3
    occupancy_timeout: 180
    illuminance_below_threshold_check: true
    icon: device_icons/30364a70dbf761633ccf58fb78c27b0b.png
  '0xd0cf5efffec7e1fb':
    friendly_name: Office Cabinets Inside
    icon: device_icons/38c2d71f8cab4db2b412c003d39c4a56.png
  '0x588e81fffe6c99fd':
    friendly_name: Office Cabinets Front
    homeassistant:
      name: Office Cabinets Front
    legacy: false
    optimistic: true
    icon: device_icons/38c2d71f8cab4db2b412c003d39c4a56.png
  '0xbc33acfffe3025ec':
    friendly_name: Kitchen Under Counter
    icon: device_icons/38c2d71f8cab4db2b412c003d39c4a56.png
  '0x842e14fffe7f1823':
    friendly_name: Kitchen Counter
    icon: device_icons/38c2d71f8cab4db2b412c003d39c4a56.png
  '0x804b50fffeef7a46':
    friendly_name: Kitchen Lights Remote
    legacy: false
    icon: device_icons/7146bc3333829dd31b1a37b1f83f6e01.png
  '0xbc33acfffebd4750':
    friendly_name: Office Lamp
    transition: 0
    state_action: true
    icon: device_icons/edbb776e8acea1cbcf624f5589c75ae3.png
  '0x000b57fffe978d3f':
    friendly_name: Dining Room Lamp Left
    icon: device_icons/ac9e2ef2eda38e38f2a6256ba5f02b9d.png
  '0xec1bbdfffe9eed51':
    friendly_name: Dining Room Remote
    legacy: false
    icon: device_icons/7146bc3333829dd31b1a37b1f83f6e01.png
  '0xec1bbdfffedfbba3':
    friendly_name: Living Room Cabinets Front
    icon: device_icons/38c2d71f8cab4db2b412c003d39c4a56.png
  '0x000d6ffffec3aef6':
    friendly_name: Living Room Cabinets Inside
    icon: device_icons/38c2d71f8cab4db2b412c003d39c4a56.png
  '0xbc33acfffe9e1f16':
    friendly_name: Living Room Sofa Right
    state_action: true
    icon: device_icons/edbb776e8acea1cbcf624f5589c75ae3.png
  '0xbc33acfffea1e1c6':
    friendly_name: Living Room Sofa Left
    state_action: true
    icon: device_icons/edbb776e8acea1cbcf624f5589c75ae3.png
  '0x70ac08fffeee86c6':
    friendly_name: Guest Bedroom Lamp Left
    icon: device_icons/65da2f9ea64da5100e9370c9546ff5e7.png
    state_action: false
  '0xbc33acfffea1daa2':
    friendly_name: Guest Bedroom Lamp Right
    icon: device_icons/edbb776e8acea1cbcf624f5589c75ae3.png
  '0xbc33acfffebcb527':
    friendly_name: Bedroom Lamp Left
    icon: device_icons/edbb776e8acea1cbcf624f5589c75ae3.png
  '0x000b57fffef3701e':
    friendly_name: Bedroom Remote
    legacy: false
    icon: device_icons/0bb605a453f07b8806fb5bd0288dd434.png
  '0xbc33acfffe98c391':
    friendly_name: Bedroom Lamp Right
    icon: device_icons/edbb776e8acea1cbcf624f5589c75ae3.png
  '0xd0cf5efffed992d0':
    friendly_name: Repeater
    icon: device_icons/24db05d65ad54835a329d5d5b3452222.png
  '0xa4c1382cc73f5d09':
    friendly_name: Parcel Box
    icon: device_icons/6056d088143bc1eadebd8cd0cfec5368.png
  '0x000b57fffeb19864':
    friendly_name: Outside 4 Down
    icon: device_icons/3d85b85d25db2fcadb59a16e22bb8d54.png
  '0x000b57fffebf28bc':
    friendly_name: Outside 3 Up
    icon: device_icons/3d85b85d25db2fcadb59a16e22bb8d54.png
  '0x000b57fffebefcf4':
    friendly_name: Outside 5 Down
    icon: device_icons/3d85b85d25db2fcadb59a16e22bb8d54.png
  '0x000b57fffebed036':
    friendly_name: Outside 3 Down
    icon: device_icons/3d85b85d25db2fcadb59a16e22bb8d54.png
  '0x000b57fffe520a0e':
    friendly_name: Outside 1 Up
    icon: device_icons/3d85b85d25db2fcadb59a16e22bb8d54.png
  '0x000b57fffeaffb7b':
    friendly_name: Outside 4 Up
    icon: device_icons/3d85b85d25db2fcadb59a16e22bb8d54.png
  '0x842e14fffe605be8':
    friendly_name: Outside 2 Down
    icon: device_icons/ba883617d108de69a0d5a397a203e979.png
  '0x000b57fffe8473b8':
    friendly_name: Outside 2 Up
    icon: device_icons/3d85b85d25db2fcadb59a16e22bb8d54.png
  '0xa4c1383ed970356b':
    friendly_name: 'Garage Door Sensor '
    icon: device_icons/67d8a38ea355da6e701908018fd64f87.png
  '0xa4c1387ab3af9d49':
    friendly_name: Back Door Sensor
    icon: device_icons/67d8a38ea355da6e701908018fd64f87.png
  '0xa4c138fdb6272825':
    friendly_name: 'Front Door Sensor '
    icon: device_icons/67d8a38ea355da6e701908018fd64f87.png
  '0x000b57fffe27203b':
    friendly_name: Dining Room Lamp Right
    icon: device_icons/ac9e2ef2eda38e38f2a6256ba5f02b9d.png
  '0x943469fffe5fb1a8':
    friendly_name: Outside 1 Down
    state_action: false
    icon: device_icons/d2e0653afd58b1b387308aac0b1b7dc6.png
  '0x588e81fffe3ea2da':
    friendly_name: Kitchen Action Button
    legacy: false
    icon: device_icons/7146bc3333829dd31b1a37b1f83f6e01.png
  '0x680ae2fffe8125b0':
    friendly_name: '0x680ae2fffe8125b0'
    legacy: false
    icon: device_icons/7146bc3333829dd31b1a37b1f83f6e01.png
  '0x60a423fffeadc632':
    friendly_name: Bedroom Bedside Remote
    legacy: true
    icon: device_icons/f1504ae638f983567e4384447325f67a.png
  '0x588e81fffe76d0ad':
    friendly_name: Kitchen Cabinet
    state_action: false
    icon: device_icons/411c97850db9a9d71a184c23fa36ca82.png
  '0x1c34f1fffe7b15b8':
    friendly_name: Office Wall Lamp
    state_action: false
  '0x842e14fffe47d410':
    friendly_name: Garden 3 Down
  '0x842e14fffe4a9b04':
    friendly_name: Garden 3 Up
  '0x588e81fffe56d5bb':
    friendly_name: Garden 2 Down
  '0x588e81fffe5ee050':
    friendly_name: Garden 2 Up
  '0xbc33acfffe0e94a5':
    friendly_name: Garden 1 Down
  '0x842e14fffe75255e':
    friendly_name: Garden 1 Up
  '0xb4e3f9fffef34402':
    friendly_name: Office Remote Control
    legacy: false
  '0x000b57fffeca960f':
    friendly_name: Dining Room 2
  '0x000b57fffec56df2':
    friendly_name: Dining Room 3
  '0x000b57fffeca9028':
    friendly_name: Dining Room 1
  '0x000b57fffec56e41':
    friendly_name: Dining Room 4
  '0x000b57fffe9bad09':
    friendly_name: Kitchen Motion Sensor 1
    occupancy_timeout: 180
  '0x000b57fffe8edae5':
    friendly_name: Kitchen Motion Sensor 2
    occupancy_timeout: 180
  '0xccccccfffe924b3c':
    friendly_name: '0xccccccfffe924b3c'
  '0x0cae5ffffed03447':
    friendly_name: Office Radiator
    thermostat_unit: celsius
  '0x6c5cb1fffe6730c8':
    friendly_name: Christmas Tree Light
  '0x60a423fffef24b3b':
    friendly_name: Front Door Motion Sensor
  '0x842e14fffe422e7a':
    friendly_name: Living Room Remote
  '0x000d6ffffe9c3ea8':
    friendly_name: Office Blind Remote
availability:
  enabled: true
  active:
    timeout: 10
  passive:
    timeout: 1500
groups:
  '1':
    friendly_name: Dining Room Lights
  '2':
    friendly_name: Dining Room Ceiling Lights
  '3':
    friendly_name: Living Room Lights
  '4':
    friendly_name: Bedroom Lights
  '5':
    friendly_name: Guest Bedroom Lights
  '6':
    friendly_name: Office Lights
  '7':
    friendly_name: Kitchen Lights
  '8':
    friendly_name: Outside Lights
  '9':
    friendly_name: Garden Lights
  '10':
    friendly_name: Dining Room Side Lamps
version: 4
